/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.tiendaenlinea.negocio.examples;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import edu.co.sena.tiendaenlinea.integracion.dao.PagoDao;
import edu.co.sena.tiendaenlinea.integracion.dto.Pago;
import edu.co.sena.tiendaenlinea.integracion.exceptions.PagoDaoException;
import edu.co.sena.tiendaenlinea.integracion.factory.PagoDaoFactory;

public class PagoDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findByFactura(0);
		// findWhereFacturaIdfacturaEquals(0);
		// findWhereNumTarCreditoEquals("");
		// findWhereBancoEquals("");
		// findWhereTipoCuentaTarEquals("");
		// findWhereTipoTransaccionEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			PagoDao _dao = getPagoDao();
			Pago _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByFactura'
	 * 
	 * @param facturaIdfactura
	 */
	public static void findByFactura(int facturaIdfactura)
	{
		try {
			PagoDao _dao = getPagoDao();
			Pago _result[] = _dao.findByFactura(facturaIdfactura);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereFacturaIdfacturaEquals'
	 * 
	 * @param facturaIdfactura
	 */
	public static void findWhereFacturaIdfacturaEquals(int facturaIdfactura)
	{
		try {
			PagoDao _dao = getPagoDao();
			Pago _result[] = _dao.findWhereFacturaIdfacturaEquals(facturaIdfactura);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNumTarCreditoEquals'
	 * 
	 * @param numTarCredito
	 */
	public static void findWhereNumTarCreditoEquals(String numTarCredito)
	{
		try {
			PagoDao _dao = getPagoDao();
			Pago _result[] = _dao.findWhereNumTarCreditoEquals(numTarCredito);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereBancoEquals'
	 * 
	 * @param banco
	 */
	public static void findWhereBancoEquals(String banco)
	{
		try {
			PagoDao _dao = getPagoDao();
			Pago _result[] = _dao.findWhereBancoEquals(banco);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereTipoCuentaTarEquals'
	 * 
	 * @param tipoCuentaTar
	 */
	public static void findWhereTipoCuentaTarEquals(String tipoCuentaTar)
	{
		try {
			PagoDao _dao = getPagoDao();
			Pago _result[] = _dao.findWhereTipoCuentaTarEquals(tipoCuentaTar);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereTipoTransaccionEquals'
	 * 
	 * @param tipoTransaccion
	 */
	public static void findWhereTipoTransaccionEquals(String tipoTransaccion)
	{
		try {
			PagoDao _dao = getPagoDao();
			Pago _result[] = _dao.findWhereTipoTransaccionEquals(tipoTransaccion);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getPagoDao'
	 * 
	 * @return PagoDao
	 */
	public static PagoDao getPagoDao()
	{
		return PagoDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Pago dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getFacturaIdfactura() );
		buf.append( ", " );
		buf.append( dto.getNumTarCredito() );
		buf.append( ", " );
		buf.append( dto.getBanco() );
		buf.append( ", " );
		buf.append( dto.getTipoCuentaTar() );
		buf.append( ", " );
		buf.append( dto.getTipoTransaccion() );
		System.out.println( buf.toString() );
	}

}
