/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.tiendaenlinea.integracion.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the inventario table.
 */
public class InventarioPk implements Serializable
{
	protected int idInventario;

	protected String productoIdproducto;

	protected String proveedorIdproveedor;

	protected String proveedorTipodeidentificacion;

	/** 
	 * This attribute represents whether the primitive attribute idInventario is null.
	 */
	protected boolean idInventarioNull;

	/** 
	 * Sets the value of idInventario
	 */
	public void setIdInventario(int idInventario)
	{
		this.idInventario = idInventario;
	}

	/** 
	 * Gets the value of idInventario
	 */
	public int getIdInventario()
	{
		return idInventario;
	}

	/** 
	 * Sets the value of productoIdproducto
	 */
	public void setProductoIdproducto(String productoIdproducto)
	{
		this.productoIdproducto = productoIdproducto;
	}

	/** 
	 * Gets the value of productoIdproducto
	 */
	public String getProductoIdproducto()
	{
		return productoIdproducto;
	}

	/** 
	 * Sets the value of proveedorIdproveedor
	 */
	public void setProveedorIdproveedor(String proveedorIdproveedor)
	{
		this.proveedorIdproveedor = proveedorIdproveedor;
	}

	/** 
	 * Gets the value of proveedorIdproveedor
	 */
	public String getProveedorIdproveedor()
	{
		return proveedorIdproveedor;
	}

	/** 
	 * Sets the value of proveedorTipodeidentificacion
	 */
	public void setProveedorTipodeidentificacion(String proveedorTipodeidentificacion)
	{
		this.proveedorTipodeidentificacion = proveedorTipodeidentificacion;
	}

	/** 
	 * Gets the value of proveedorTipodeidentificacion
	 */
	public String getProveedorTipodeidentificacion()
	{
		return proveedorTipodeidentificacion;
	}

	/**
	 * Method 'InventarioPk'
	 * 
	 */
	public InventarioPk()
	{
	}

	/**
	 * Method 'InventarioPk'
	 * 
	 * @param idInventario
	 * @param productoIdproducto
	 * @param proveedorIdproveedor
	 * @param proveedorTipodeidentificacion
	 */
	public InventarioPk(final int idInventario, final String productoIdproducto, final String proveedorIdproveedor, final String proveedorTipodeidentificacion)
	{
		this.idInventario = idInventario;
		this.productoIdproducto = productoIdproducto;
		this.proveedorIdproveedor = proveedorIdproveedor;
		this.proveedorTipodeidentificacion = proveedorTipodeidentificacion;
	}

	/** 
	 * Sets the value of idInventarioNull
	 */
	public void setIdInventarioNull(boolean idInventarioNull)
	{
		this.idInventarioNull = idInventarioNull;
	}

	/** 
	 * Gets the value of idInventarioNull
	 */
	public boolean isIdInventarioNull()
	{
		return idInventarioNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof InventarioPk)) {
			return false;
		}
		
		final InventarioPk _cast = (InventarioPk) _other;
		if (idInventario != _cast.idInventario) {
			return false;
		}
		
		if (productoIdproducto == null ? _cast.productoIdproducto != productoIdproducto : !productoIdproducto.equals( _cast.productoIdproducto )) {
			return false;
		}
		
		if (proveedorIdproveedor == null ? _cast.proveedorIdproveedor != proveedorIdproveedor : !proveedorIdproveedor.equals( _cast.proveedorIdproveedor )) {
			return false;
		}
		
		if (proveedorTipodeidentificacion == null ? _cast.proveedorTipodeidentificacion != proveedorTipodeidentificacion : !proveedorTipodeidentificacion.equals( _cast.proveedorTipodeidentificacion )) {
			return false;
		}
		
		if (idInventarioNull != _cast.idInventarioNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idInventario;
		if (productoIdproducto != null) {
			_hashCode = 29 * _hashCode + productoIdproducto.hashCode();
		}
		
		if (proveedorIdproveedor != null) {
			_hashCode = 29 * _hashCode + proveedorIdproveedor.hashCode();
		}
		
		if (proveedorTipodeidentificacion != null) {
			_hashCode = 29 * _hashCode + proveedorTipodeidentificacion.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (idInventarioNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.tiendaenlinea.integracion.dto.InventarioPk: " );
		ret.append( "idInventario=" + idInventario );
		ret.append( ", productoIdproducto=" + productoIdproducto );
		ret.append( ", proveedorIdproveedor=" + proveedorIdproveedor );
		ret.append( ", proveedorTipodeidentificacion=" + proveedorTipodeidentificacion );
		return ret.toString();
	}

}
