/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.tiendaenlinea.integracion.dto;

import edu.co.sena.tiendaenlinea.integracion.dao.*;
import edu.co.sena.tiendaenlinea.integracion.factory.*;
import edu.co.sena.tiendaenlinea.integracion.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Pago implements Serializable
{
	/** 
	 * This attribute maps to the column Factura_idFactura in the pago table.
	 */
	protected int facturaIdfactura;

	/** 
	 * This attribute represents whether the attribute facturaIdfactura has been modified since being read from the database.
	 */
	protected boolean facturaIdfacturaModified = false;

	/** 
	 * This attribute maps to the column numTarCredito in the pago table.
	 */
	protected String numTarCredito;

	/** 
	 * This attribute represents whether the attribute numTarCredito has been modified since being read from the database.
	 */
	protected boolean numTarCreditoModified = false;

	/** 
	 * This attribute maps to the column banco in the pago table.
	 */
	protected String banco;

	/** 
	 * This attribute represents whether the attribute banco has been modified since being read from the database.
	 */
	protected boolean bancoModified = false;

	/** 
	 * This attribute maps to the column tipoCuentaTar in the pago table.
	 */
	protected String tipoCuentaTar;

	/** 
	 * This attribute represents whether the attribute tipoCuentaTar has been modified since being read from the database.
	 */
	protected boolean tipoCuentaTarModified = false;

	/** 
	 * This attribute maps to the column tipoTransaccion in the pago table.
	 */
	protected String tipoTransaccion;

	/** 
	 * This attribute represents whether the attribute tipoTransaccion has been modified since being read from the database.
	 */
	protected boolean tipoTransaccionModified = false;

	/**
	 * Method 'Pago'
	 * 
	 */
	public Pago()
	{
	}

	/**
	 * Method 'getFacturaIdfactura'
	 * 
	 * @return int
	 */
	public int getFacturaIdfactura()
	{
		return facturaIdfactura;
	}

	/**
	 * Method 'setFacturaIdfactura'
	 * 
	 * @param facturaIdfactura
	 */
	public void setFacturaIdfactura(int facturaIdfactura)
	{
		this.facturaIdfactura = facturaIdfactura;
		this.facturaIdfacturaModified = true;
	}

	/** 
	 * Sets the value of facturaIdfacturaModified
	 */
	public void setFacturaIdfacturaModified(boolean facturaIdfacturaModified)
	{
		this.facturaIdfacturaModified = facturaIdfacturaModified;
	}

	/** 
	 * Gets the value of facturaIdfacturaModified
	 */
	public boolean isFacturaIdfacturaModified()
	{
		return facturaIdfacturaModified;
	}

	/**
	 * Method 'getNumTarCredito'
	 * 
	 * @return String
	 */
	public String getNumTarCredito()
	{
		return numTarCredito;
	}

	/**
	 * Method 'setNumTarCredito'
	 * 
	 * @param numTarCredito
	 */
	public void setNumTarCredito(String numTarCredito)
	{
		this.numTarCredito = numTarCredito;
		this.numTarCreditoModified = true;
	}

	/** 
	 * Sets the value of numTarCreditoModified
	 */
	public void setNumTarCreditoModified(boolean numTarCreditoModified)
	{
		this.numTarCreditoModified = numTarCreditoModified;
	}

	/** 
	 * Gets the value of numTarCreditoModified
	 */
	public boolean isNumTarCreditoModified()
	{
		return numTarCreditoModified;
	}

	/**
	 * Method 'getBanco'
	 * 
	 * @return String
	 */
	public String getBanco()
	{
		return banco;
	}

	/**
	 * Method 'setBanco'
	 * 
	 * @param banco
	 */
	public void setBanco(String banco)
	{
		this.banco = banco;
		this.bancoModified = true;
	}

	/** 
	 * Sets the value of bancoModified
	 */
	public void setBancoModified(boolean bancoModified)
	{
		this.bancoModified = bancoModified;
	}

	/** 
	 * Gets the value of bancoModified
	 */
	public boolean isBancoModified()
	{
		return bancoModified;
	}

	/**
	 * Method 'getTipoCuentaTar'
	 * 
	 * @return String
	 */
	public String getTipoCuentaTar()
	{
		return tipoCuentaTar;
	}

	/**
	 * Method 'setTipoCuentaTar'
	 * 
	 * @param tipoCuentaTar
	 */
	public void setTipoCuentaTar(String tipoCuentaTar)
	{
		this.tipoCuentaTar = tipoCuentaTar;
		this.tipoCuentaTarModified = true;
	}

	/** 
	 * Sets the value of tipoCuentaTarModified
	 */
	public void setTipoCuentaTarModified(boolean tipoCuentaTarModified)
	{
		this.tipoCuentaTarModified = tipoCuentaTarModified;
	}

	/** 
	 * Gets the value of tipoCuentaTarModified
	 */
	public boolean isTipoCuentaTarModified()
	{
		return tipoCuentaTarModified;
	}

	/**
	 * Method 'getTipoTransaccion'
	 * 
	 * @return String
	 */
	public String getTipoTransaccion()
	{
		return tipoTransaccion;
	}

	/**
	 * Method 'setTipoTransaccion'
	 * 
	 * @param tipoTransaccion
	 */
	public void setTipoTransaccion(String tipoTransaccion)
	{
		this.tipoTransaccion = tipoTransaccion;
		this.tipoTransaccionModified = true;
	}

	/** 
	 * Sets the value of tipoTransaccionModified
	 */
	public void setTipoTransaccionModified(boolean tipoTransaccionModified)
	{
		this.tipoTransaccionModified = tipoTransaccionModified;
	}

	/** 
	 * Gets the value of tipoTransaccionModified
	 */
	public boolean isTipoTransaccionModified()
	{
		return tipoTransaccionModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Pago)) {
			return false;
		}
		
		final Pago _cast = (Pago) _other;
		if (facturaIdfactura != _cast.facturaIdfactura) {
			return false;
		}
		
		if (facturaIdfacturaModified != _cast.facturaIdfacturaModified) {
			return false;
		}
		
		if (numTarCredito == null ? _cast.numTarCredito != numTarCredito : !numTarCredito.equals( _cast.numTarCredito )) {
			return false;
		}
		
		if (numTarCreditoModified != _cast.numTarCreditoModified) {
			return false;
		}
		
		if (banco == null ? _cast.banco != banco : !banco.equals( _cast.banco )) {
			return false;
		}
		
		if (bancoModified != _cast.bancoModified) {
			return false;
		}
		
		if (tipoCuentaTar == null ? _cast.tipoCuentaTar != tipoCuentaTar : !tipoCuentaTar.equals( _cast.tipoCuentaTar )) {
			return false;
		}
		
		if (tipoCuentaTarModified != _cast.tipoCuentaTarModified) {
			return false;
		}
		
		if (tipoTransaccion == null ? _cast.tipoTransaccion != tipoTransaccion : !tipoTransaccion.equals( _cast.tipoTransaccion )) {
			return false;
		}
		
		if (tipoTransaccionModified != _cast.tipoTransaccionModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + facturaIdfactura;
		_hashCode = 29 * _hashCode + (facturaIdfacturaModified ? 1 : 0);
		if (numTarCredito != null) {
			_hashCode = 29 * _hashCode + numTarCredito.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (numTarCreditoModified ? 1 : 0);
		if (banco != null) {
			_hashCode = 29 * _hashCode + banco.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (bancoModified ? 1 : 0);
		if (tipoCuentaTar != null) {
			_hashCode = 29 * _hashCode + tipoCuentaTar.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (tipoCuentaTarModified ? 1 : 0);
		if (tipoTransaccion != null) {
			_hashCode = 29 * _hashCode + tipoTransaccion.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (tipoTransaccionModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return PagoPk
	 */
	public PagoPk createPk()
	{
		return new PagoPk(facturaIdfactura);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.tiendaenlinea.integracion.dto.Pago: " );
		ret.append( "facturaIdfactura=" + facturaIdfactura );
		ret.append( ", numTarCredito=" + numTarCredito );
		ret.append( ", banco=" + banco );
		ret.append( ", tipoCuentaTar=" + tipoCuentaTar );
		ret.append( ", tipoTransaccion=" + tipoTransaccion );
		return ret.toString();
	}

}
