INSERT INTO `tiendaenlinea`.`departamento`(`idDepartamento`,`nombre`)VALUES('1','AMAZONAS');
INSERT INTO `tiendaenlinea`.`departamento`(`idDepartamento`,`nombre`)VALUES('2','ANTIOQUIA');
INSERT INTO `tiendaenlinea`.`departamento`(`idDepartamento`,`nombre`)VALUES('3','ARAUCA');
INSERT INTO `tiendaenlinea`.`departamento`(`idDepartamento`,`nombre`)VALUES('4','ATLÁNTICO');
INSERT INTO `tiendaenlinea`.`departamento`(`idDepartamento`,`nombre`)VALUES('5','BOLÍVAR');
INSERT INTO `tiendaenlinea`.`departamento`(`idDepartamento`,`nombre`)VALUES('6','BOYACÁ');
INSERT INTO `tiendaenlinea`.`departamento`(`idDepartamento`,`nombre`)VALUES('7','CALDAS');
INSERT INTO `tiendaenlinea`.`departamento`(`idDepartamento`,`nombre`)VALUES('8','CAQUETÁ');
INSERT INTO `tiendaenlinea`.`departamento`(`idDepartamento`,`nombre`)VALUES('9','CASANARE');
INSERT INTO `tiendaenlinea`.`departamento`(`idDepartamento`,`nombre`)VALUES('10','CAUCA');
INSERT INTO `tiendaenlinea`.`departamento`(`idDepartamento`,`nombre`)VALUES('11','CESAR');
INSERT INTO `tiendaenlinea`.`departamento`(`idDepartamento`,`nombre`)VALUES('12','CHOCÓ');
INSERT INTO `tiendaenlinea`.`departamento`(`idDepartamento`,`nombre`)VALUES('13','CÓRDOBA');
INSERT INTO `tiendaenlinea`.`departamento`(`idDepartamento`,`nombre`)VALUES('14','CUNDINAMARCA');
INSERT INTO `tiendaenlinea`.`departamento`(`idDepartamento`,`nombre`)VALUES('15','GUAINÍA');
INSERT INTO `tiendaenlinea`.`departamento`(`idDepartamento`,`nombre`)VALUES('16','GUAVIARE');
INSERT INTO `tiendaenlinea`.`departamento`(`idDepartamento`,`nombre`)VALUES('17','HUILA');
INSERT INTO `tiendaenlinea`.`departamento`(`idDepartamento`,`nombre`)VALUES('18','LA GUAJIRA');
INSERT INTO `tiendaenlinea`.`departamento`(`idDepartamento`,`nombre`)VALUES('19','MAGDALENA');
INSERT INTO `tiendaenlinea`.`departamento`(`idDepartamento`,`nombre`)VALUES('20','META');
INSERT INTO `tiendaenlinea`.`departamento`(`idDepartamento`,`nombre`)VALUES('21','NARIÑO');
INSERT INTO `tiendaenlinea`.`departamento`(`idDepartamento`,`nombre`)VALUES('22','NORTE DE SANTANDER');
INSERT INTO `tiendaenlinea`.`departamento`(`idDepartamento`,`nombre`)VALUES('23','PUTUMAYO');
INSERT INTO `tiendaenlinea`.`departamento`(`idDepartamento`,`nombre`)VALUES('24','QUINDÍO');
INSERT INTO `tiendaenlinea`.`departamento`(`idDepartamento`,`nombre`)VALUES('25','RISARALDA');
INSERT INTO `tiendaenlinea`.`departamento`(`idDepartamento`,`nombre`)VALUES('26','SAN ANDRÉS Y ROVIDENCIA');
INSERT INTO `tiendaenlinea`.`departamento`(`idDepartamento`,`nombre`)VALUES('27','SANTANDER');
INSERT INTO `tiendaenlinea`.`departamento`(`idDepartamento`,`nombre`)VALUES('28','SUCRE');
INSERT INTO `tiendaenlinea`.`departamento`(`idDepartamento`,`nombre`)VALUES('29','TOLIMA');
INSERT INTO `tiendaenlinea`.`departamento`(`idDepartamento`,`nombre`)VALUES('30','VALLE DEL CAUCA');
INSERT INTO `tiendaenlinea`.`departamento`(`idDepartamento`,`nombre`)VALUES('31','VAUPÉS');
INSERT INTO `tiendaenlinea`.`departamento`(`idDepartamento`,`nombre`)VALUES('32','VICHADA');