/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.tiendaenlinea.integracion.jdbc;

import edu.co.sena.tiendaenlinea.integracion.dao.*;
import edu.co.sena.tiendaenlinea.integracion.factory.*;
import edu.co.sena.tiendaenlinea.integracion.dto.*;
import edu.co.sena.tiendaenlinea.integracion.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class ItemCarritoDaoImpl extends AbstractDAO implements ItemCarritoDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT Producto_idProducto, CarritoDeCompras_idCarritoDeCompras, cantidad, costoUnitario, costoTotal FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( Producto_idProducto, CarritoDeCompras_idCarritoDeCompras, cantidad, costoUnitario, costoTotal ) VALUES ( ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET Producto_idProducto = ?, CarritoDeCompras_idCarritoDeCompras = ?, cantidad = ?, costoUnitario = ?, costoTotal = ? WHERE Producto_idProducto = ? AND CarritoDeCompras_idCarritoDeCompras = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE Producto_idProducto = ? AND CarritoDeCompras_idCarritoDeCompras = ?";

	/** 
	 * Index of column Producto_idProducto
	 */
	protected static final int COLUMN_PRODUCTO_IDPRODUCTO = 1;

	/** 
	 * Index of column CarritoDeCompras_idCarritoDeCompras
	 */
	protected static final int COLUMN_CARRITODECOMPRAS_IDCARRITODECOMPRAS = 2;

	/** 
	 * Index of column cantidad
	 */
	protected static final int COLUMN_CANTIDAD = 3;

	/** 
	 * Index of column costoUnitario
	 */
	protected static final int COLUMN_COSTO_UNITARIO = 4;

	/** 
	 * Index of column costoTotal
	 */
	protected static final int COLUMN_COSTO_TOTAL = 5;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 5;

	/** 
	 * Index of primary-key column Producto_idProducto
	 */
	protected static final int PK_COLUMN_PRODUCTO_IDPRODUCTO = 1;

	/** 
	 * Index of primary-key column CarritoDeCompras_idCarritoDeCompras
	 */
	protected static final int PK_COLUMN_CARRITODECOMPRAS_IDCARRITODECOMPRAS = 2;

	/** 
	 * Inserts a new row in the item_carrito table.
	 */
	public ItemCarritoPk insert(ItemCarrito dto) throws ItemCarritoDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			StringBuffer values = new StringBuffer();
			sql.append( "INSERT INTO " + getTableName() + " (" );
			int modifiedCount = 0;
			if (dto.isProductoIdproductoModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "Producto_idProducto" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isCarritodecomprasIdcarritodecomprasModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "CarritoDeCompras_idCarritoDeCompras" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isCantidadModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "cantidad" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isCostoUnitarioModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "costoUnitario" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isCostoTotalModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "costoTotal" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (modifiedCount==0) {
				// nothing to insert
				throw new IllegalStateException( "Nothing to insert" );
			}
		
			sql.append( ") VALUES (" );
			sql.append( values );
			sql.append( ")" );
			stmt = conn.prepareStatement( sql.toString() );
			int index = 1;
			if (dto.isProductoIdproductoModified()) {
				stmt.setString( index++, dto.getProductoIdproducto() );
			}
		
			if (dto.isCarritodecomprasIdcarritodecomprasModified()) {
				stmt.setString( index++, dto.getCarritodecomprasIdcarritodecompras() );
			}
		
			if (dto.isCantidadModified()) {
				stmt.setInt( index++, dto.getCantidad() );
			}
		
			if (dto.isCostoUnitarioModified()) {
				stmt.setFloat( index++, dto.getCostoUnitario() );
			}
		
			if (dto.isCostoTotalModified()) {
				stmt.setFloat( index++, dto.getCostoTotal() );
			}
		
			System.out.println( "Executing " + sql.toString() + " with values: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ItemCarritoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the item_carrito table.
	 */
	public void update(ItemCarritoPk pk, ItemCarrito dto) throws ItemCarritoDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			sql.append( "UPDATE " + getTableName() + " SET " );
			boolean modified = false;
			if (dto.isProductoIdproductoModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "Producto_idProducto=?" );
				modified=true;
			}
		
			if (dto.isCarritodecomprasIdcarritodecomprasModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "CarritoDeCompras_idCarritoDeCompras=?" );
				modified=true;
			}
		
			if (dto.isCantidadModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "cantidad=?" );
				modified=true;
			}
		
			if (dto.isCostoUnitarioModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "costoUnitario=?" );
				modified=true;
			}
		
			if (dto.isCostoTotalModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "costoTotal=?" );
				modified=true;
			}
		
			if (!modified) {
				// nothing to update
				return;
			}
		
			sql.append( " WHERE Producto_idProducto=? AND CarritoDeCompras_idCarritoDeCompras=?" );
			System.out.println( "Executing " + sql.toString() + " with values: " + dto );
			stmt = conn.prepareStatement( sql.toString() );
			int index = 1;
			if (dto.isProductoIdproductoModified()) {
				stmt.setString( index++, dto.getProductoIdproducto() );
			}
		
			if (dto.isCarritodecomprasIdcarritodecomprasModified()) {
				stmt.setString( index++, dto.getCarritodecomprasIdcarritodecompras() );
			}
		
			if (dto.isCantidadModified()) {
				stmt.setInt( index++, dto.getCantidad() );
			}
		
			if (dto.isCostoUnitarioModified()) {
				stmt.setFloat( index++, dto.getCostoUnitario() );
			}
		
			if (dto.isCostoTotalModified()) {
				stmt.setFloat( index++, dto.getCostoTotal() );
			}
		
			stmt.setString( index++, pk.getProductoIdproducto() );
			stmt.setString( index++, pk.getCarritodecomprasIdcarritodecompras() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ItemCarritoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the item_carrito table.
	 */
	public void delete(ItemCarritoPk pk) throws ItemCarritoDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setString( 1, pk.getProductoIdproducto() );
			stmt.setString( 2, pk.getCarritodecomprasIdcarritodecompras() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ItemCarritoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the item_carrito table that matches the specified primary-key value.
	 */
	public ItemCarrito findByPrimaryKey(ItemCarritoPk pk) throws ItemCarritoDaoException
	{
		return findByPrimaryKey( pk.getProductoIdproducto(), pk.getCarritodecomprasIdcarritodecompras() );
	}

	/** 
	 * Returns all rows from the item_carrito table that match the criteria 'Producto_idProducto = :productoIdproducto AND CarritoDeCompras_idCarritoDeCompras = :carritodecomprasIdcarritodecompras'.
	 */
	public ItemCarrito findByPrimaryKey(String productoIdproducto, String carritodecomprasIdcarritodecompras) throws ItemCarritoDaoException
	{
		ItemCarrito ret[] = findByDynamicSelect( SQL_SELECT + " WHERE Producto_idProducto = ? AND CarritoDeCompras_idCarritoDeCompras = ?", new Object[] { productoIdproducto, carritodecomprasIdcarritodecompras } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the item_carrito table that match the criteria ''.
	 */
	public ItemCarrito[] findAll() throws ItemCarritoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY Producto_idProducto, CarritoDeCompras_idCarritoDeCompras", null );
	}

	/** 
	 * Returns all rows from the item_carrito table that match the criteria 'CarritoDeCompras_idCarritoDeCompras = :carritodecomprasIdcarritodecompras'.
	 */
	public ItemCarrito[] findByCarritodecompras(String carritodecomprasIdcarritodecompras) throws ItemCarritoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CarritoDeCompras_idCarritoDeCompras = ?", new Object[] { carritodecomprasIdcarritodecompras } );
	}

	/** 
	 * Returns all rows from the item_carrito table that match the criteria 'Producto_idProducto = :productoIdproducto'.
	 */
	public ItemCarrito[] findByProducto(String productoIdproducto) throws ItemCarritoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Producto_idProducto = ?", new Object[] { productoIdproducto } );
	}

	/** 
	 * Returns all rows from the item_carrito table that match the criteria 'Producto_idProducto = :productoIdproducto'.
	 */
	public ItemCarrito[] findWhereProductoIdproductoEquals(String productoIdproducto) throws ItemCarritoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Producto_idProducto = ? ORDER BY Producto_idProducto", new Object[] { productoIdproducto } );
	}

	/** 
	 * Returns all rows from the item_carrito table that match the criteria 'CarritoDeCompras_idCarritoDeCompras = :carritodecomprasIdcarritodecompras'.
	 */
	public ItemCarrito[] findWhereCarritodecomprasIdcarritodecomprasEquals(String carritodecomprasIdcarritodecompras) throws ItemCarritoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CarritoDeCompras_idCarritoDeCompras = ? ORDER BY CarritoDeCompras_idCarritoDeCompras", new Object[] { carritodecomprasIdcarritodecompras } );
	}

	/** 
	 * Returns all rows from the item_carrito table that match the criteria 'cantidad = :cantidad'.
	 */
	public ItemCarrito[] findWhereCantidadEquals(int cantidad) throws ItemCarritoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE cantidad = ? ORDER BY cantidad", new Object[] {  new Integer(cantidad) } );
	}

	/** 
	 * Returns all rows from the item_carrito table that match the criteria 'costoUnitario = :costoUnitario'.
	 */
	public ItemCarrito[] findWhereCostoUnitarioEquals(float costoUnitario) throws ItemCarritoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE costoUnitario = ? ORDER BY costoUnitario", new Object[] {  new Float(costoUnitario) } );
	}

	/** 
	 * Returns all rows from the item_carrito table that match the criteria 'costoTotal = :costoTotal'.
	 */
	public ItemCarrito[] findWhereCostoTotalEquals(float costoTotal) throws ItemCarritoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE costoTotal = ? ORDER BY costoTotal", new Object[] {  new Float(costoTotal) } );
	}

	/**
	 * Method 'ItemCarritoDaoImpl'
	 * 
	 */
	public ItemCarritoDaoImpl()
	{
	}

	/**
	 * Method 'ItemCarritoDaoImpl'
	 * 
	 * @param userConn
	 */
	public ItemCarritoDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "tiendaenlinea.item_carrito";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected ItemCarrito fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			ItemCarrito dto = new ItemCarrito();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected ItemCarrito[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			ItemCarrito dto = new ItemCarrito();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		ItemCarrito ret[] = new ItemCarrito[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(ItemCarrito dto, ResultSet rs) throws SQLException
	{
		dto.setProductoIdproducto( rs.getString( COLUMN_PRODUCTO_IDPRODUCTO ) );
		dto.setCarritodecomprasIdcarritodecompras( rs.getString( COLUMN_CARRITODECOMPRAS_IDCARRITODECOMPRAS ) );
		dto.setCantidad( rs.getInt( COLUMN_CANTIDAD ) );
		dto.setCostoUnitario( rs.getFloat( COLUMN_COSTO_UNITARIO ) );
		dto.setCostoTotal( rs.getFloat( COLUMN_COSTO_TOTAL ) );
		reset(dto);
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(ItemCarrito dto)
	{
		dto.setProductoIdproductoModified( false );
		dto.setCarritodecomprasIdcarritodecomprasModified( false );
		dto.setCantidadModified( false );
		dto.setCostoUnitarioModified( false );
		dto.setCostoTotalModified( false );
	}

	/** 
	 * Returns all rows from the item_carrito table that match the specified arbitrary SQL statement
	 */
	public ItemCarrito[] findByDynamicSelect(String sql, Object[] sqlParams) throws ItemCarritoDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ItemCarritoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the item_carrito table that match the specified arbitrary SQL statement
	 */
	public ItemCarrito[] findByDynamicWhere(String sql, Object[] sqlParams) throws ItemCarritoDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ItemCarritoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
