/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.tiendaenlinea.integracion.jdbc;

import edu.co.sena.tiendaenlinea.integracion.dao.*;
import edu.co.sena.tiendaenlinea.integracion.factory.*;
import edu.co.sena.tiendaenlinea.integracion.dto.*;
import edu.co.sena.tiendaenlinea.integracion.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class ProveedorDaoImpl extends AbstractDAO implements ProveedorDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT idProveedor, tipoDeIdentificacion, nombre, telefono, email FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( idProveedor, tipoDeIdentificacion, nombre, telefono, email ) VALUES ( ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET idProveedor = ?, tipoDeIdentificacion = ?, nombre = ?, telefono = ?, email = ? WHERE idProveedor = ? AND tipoDeIdentificacion = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE idProveedor = ? AND tipoDeIdentificacion = ?";

	/** 
	 * Index of column idProveedor
	 */
	protected static final int COLUMN_ID_PROVEEDOR = 1;

	/** 
	 * Index of column tipoDeIdentificacion
	 */
	protected static final int COLUMN_TIPO_DE_IDENTIFICACION = 2;

	/** 
	 * Index of column nombre
	 */
	protected static final int COLUMN_NOMBRE = 3;

	/** 
	 * Index of column telefono
	 */
	protected static final int COLUMN_TELEFONO = 4;

	/** 
	 * Index of column email
	 */
	protected static final int COLUMN_EMAIL = 5;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 5;

	/** 
	 * Index of primary-key column idProveedor
	 */
	protected static final int PK_COLUMN_ID_PROVEEDOR = 1;

	/** 
	 * Index of primary-key column tipoDeIdentificacion
	 */
	protected static final int PK_COLUMN_TIPO_DE_IDENTIFICACION = 2;

	/** 
	 * Inserts a new row in the proveedor table.
	 */
	public ProveedorPk insert(Proveedor dto) throws ProveedorDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setString( index++, dto.getIdProveedor() );
			stmt.setString( index++, dto.getTipoDeIdentificacion() );
			stmt.setString( index++, dto.getNombre() );
			stmt.setString( index++, dto.getTelefono() );
			stmt.setString( index++, dto.getEmail() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ProveedorDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the proveedor table.
	 */
	public void update(ProveedorPk pk, Proveedor dto) throws ProveedorDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setString( index++, dto.getIdProveedor() );
			stmt.setString( index++, dto.getTipoDeIdentificacion() );
			stmt.setString( index++, dto.getNombre() );
			stmt.setString( index++, dto.getTelefono() );
			stmt.setString( index++, dto.getEmail() );
			stmt.setString( 6, pk.getIdProveedor() );
			stmt.setString( 7, pk.getTipoDeIdentificacion() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ProveedorDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the proveedor table.
	 */
	public void delete(ProveedorPk pk) throws ProveedorDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setString( 1, pk.getIdProveedor() );
			stmt.setString( 2, pk.getTipoDeIdentificacion() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ProveedorDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the proveedor table that matches the specified primary-key value.
	 */
	public Proveedor findByPrimaryKey(ProveedorPk pk) throws ProveedorDaoException
	{
		return findByPrimaryKey( pk.getIdProveedor(), pk.getTipoDeIdentificacion() );
	}

	/** 
	 * Returns all rows from the proveedor table that match the criteria 'idProveedor = :idProveedor AND tipoDeIdentificacion = :tipoDeIdentificacion'.
	 */
	public Proveedor findByPrimaryKey(String idProveedor, String tipoDeIdentificacion) throws ProveedorDaoException
	{
		Proveedor ret[] = findByDynamicSelect( SQL_SELECT + " WHERE idProveedor = ? AND tipoDeIdentificacion = ?", new Object[] { idProveedor, tipoDeIdentificacion } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the proveedor table that match the criteria ''.
	 */
	public Proveedor[] findAll() throws ProveedorDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY idProveedor, tipoDeIdentificacion", null );
	}

	/** 
	 * Returns all rows from the proveedor table that match the criteria 'idProveedor = :idProveedor'.
	 */
	public Proveedor[] findWhereIdProveedorEquals(String idProveedor) throws ProveedorDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE idProveedor = ? ORDER BY idProveedor", new Object[] { idProveedor } );
	}

	/** 
	 * Returns all rows from the proveedor table that match the criteria 'tipoDeIdentificacion = :tipoDeIdentificacion'.
	 */
	public Proveedor[] findWhereTipoDeIdentificacionEquals(String tipoDeIdentificacion) throws ProveedorDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE tipoDeIdentificacion = ? ORDER BY tipoDeIdentificacion", new Object[] { tipoDeIdentificacion } );
	}

	/** 
	 * Returns all rows from the proveedor table that match the criteria 'nombre = :nombre'.
	 */
	public Proveedor[] findWhereNombreEquals(String nombre) throws ProveedorDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE nombre = ? ORDER BY nombre", new Object[] { nombre } );
	}

	/** 
	 * Returns all rows from the proveedor table that match the criteria 'telefono = :telefono'.
	 */
	public Proveedor[] findWhereTelefonoEquals(String telefono) throws ProveedorDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE telefono = ? ORDER BY telefono", new Object[] { telefono } );
	}

	/** 
	 * Returns all rows from the proveedor table that match the criteria 'email = :email'.
	 */
	public Proveedor[] findWhereEmailEquals(String email) throws ProveedorDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE email = ? ORDER BY email", new Object[] { email } );
	}

	/**
	 * Method 'ProveedorDaoImpl'
	 * 
	 */
	public ProveedorDaoImpl()
	{
	}

	/**
	 * Method 'ProveedorDaoImpl'
	 * 
	 * @param userConn
	 */
	public ProveedorDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "tiendaenlinea.proveedor";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Proveedor fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Proveedor dto = new Proveedor();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Proveedor[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Proveedor dto = new Proveedor();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Proveedor ret[] = new Proveedor[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Proveedor dto, ResultSet rs) throws SQLException
	{
		dto.setIdProveedor( rs.getString( COLUMN_ID_PROVEEDOR ) );
		dto.setTipoDeIdentificacion( rs.getString( COLUMN_TIPO_DE_IDENTIFICACION ) );
		dto.setNombre( rs.getString( COLUMN_NOMBRE ) );
		dto.setTelefono( rs.getString( COLUMN_TELEFONO ) );
		dto.setEmail( rs.getString( COLUMN_EMAIL ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Proveedor dto)
	{
	}

	/** 
	 * Returns all rows from the proveedor table that match the specified arbitrary SQL statement
	 */
	public Proveedor[] findByDynamicSelect(String sql, Object[] sqlParams) throws ProveedorDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ProveedorDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the proveedor table that match the specified arbitrary SQL statement
	 */
	public Proveedor[] findByDynamicWhere(String sql, Object[] sqlParams) throws ProveedorDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ProveedorDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
