/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.tiendaenlinea.integracion.dto;

import edu.co.sena.tiendaenlinea.integracion.dao.*;
import edu.co.sena.tiendaenlinea.integracion.factory.*;
import edu.co.sena.tiendaenlinea.integracion.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Departamento implements Serializable
{
	/** 
	 * This attribute maps to the column idDepartamento in the departamento table.
	 */
	protected String idDepartamento;

	/** 
	 * This attribute maps to the column nombre in the departamento table.
	 */
	protected String nombre;

	/**
	 * Method 'Departamento'
	 * 
	 */
	public Departamento()
	{
	}

	/**
	 * Method 'getIdDepartamento'
	 * 
	 * @return String
	 */
	public String getIdDepartamento()
	{
		return idDepartamento;
	}

	/**
	 * Method 'setIdDepartamento'
	 * 
	 * @param idDepartamento
	 */
	public void setIdDepartamento(String idDepartamento)
	{
		this.idDepartamento = idDepartamento;
	}

	/**
	 * Method 'getNombre'
	 * 
	 * @return String
	 */
	public String getNombre()
	{
		return nombre;
	}

	/**
	 * Method 'setNombre'
	 * 
	 * @param nombre
	 */
	public void setNombre(String nombre)
	{
		this.nombre = nombre;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Departamento)) {
			return false;
		}
		
		final Departamento _cast = (Departamento) _other;
		if (idDepartamento == null ? _cast.idDepartamento != idDepartamento : !idDepartamento.equals( _cast.idDepartamento )) {
			return false;
		}
		
		if (nombre == null ? _cast.nombre != nombre : !nombre.equals( _cast.nombre )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idDepartamento != null) {
			_hashCode = 29 * _hashCode + idDepartamento.hashCode();
		}
		
		if (nombre != null) {
			_hashCode = 29 * _hashCode + nombre.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return DepartamentoPk
	 */
	public DepartamentoPk createPk()
	{
		return new DepartamentoPk(idDepartamento);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.tiendaenlinea.integracion.dto.Departamento: " );
		ret.append( "idDepartamento=" + idDepartamento );
		ret.append( ", nombre=" + nombre );
		return ret.toString();
	}

}
