/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.tiendaenlinea.integracion.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the domicilio_proveedor table.
 */
public class DomicilioProveedorPk implements Serializable
{
	protected String proveedorIdproveedor;

	protected String proveedorTipodeidentificacion;

	/** 
	 * Sets the value of proveedorIdproveedor
	 */
	public void setProveedorIdproveedor(String proveedorIdproveedor)
	{
		this.proveedorIdproveedor = proveedorIdproveedor;
	}

	/** 
	 * Gets the value of proveedorIdproveedor
	 */
	public String getProveedorIdproveedor()
	{
		return proveedorIdproveedor;
	}

	/** 
	 * Sets the value of proveedorTipodeidentificacion
	 */
	public void setProveedorTipodeidentificacion(String proveedorTipodeidentificacion)
	{
		this.proveedorTipodeidentificacion = proveedorTipodeidentificacion;
	}

	/** 
	 * Gets the value of proveedorTipodeidentificacion
	 */
	public String getProveedorTipodeidentificacion()
	{
		return proveedorTipodeidentificacion;
	}

	/**
	 * Method 'DomicilioProveedorPk'
	 * 
	 */
	public DomicilioProveedorPk()
	{
	}

	/**
	 * Method 'DomicilioProveedorPk'
	 * 
	 * @param proveedorIdproveedor
	 * @param proveedorTipodeidentificacion
	 */
	public DomicilioProveedorPk(final String proveedorIdproveedor, final String proveedorTipodeidentificacion)
	{
		this.proveedorIdproveedor = proveedorIdproveedor;
		this.proveedorTipodeidentificacion = proveedorTipodeidentificacion;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof DomicilioProveedorPk)) {
			return false;
		}
		
		final DomicilioProveedorPk _cast = (DomicilioProveedorPk) _other;
		if (proveedorIdproveedor == null ? _cast.proveedorIdproveedor != proveedorIdproveedor : !proveedorIdproveedor.equals( _cast.proveedorIdproveedor )) {
			return false;
		}
		
		if (proveedorTipodeidentificacion == null ? _cast.proveedorTipodeidentificacion != proveedorTipodeidentificacion : !proveedorTipodeidentificacion.equals( _cast.proveedorTipodeidentificacion )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (proveedorIdproveedor != null) {
			_hashCode = 29 * _hashCode + proveedorIdproveedor.hashCode();
		}
		
		if (proveedorTipodeidentificacion != null) {
			_hashCode = 29 * _hashCode + proveedorTipodeidentificacion.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.tiendaenlinea.integracion.dto.DomicilioProveedorPk: " );
		ret.append( "proveedorIdproveedor=" + proveedorIdproveedor );
		ret.append( ", proveedorTipodeidentificacion=" + proveedorTipodeidentificacion );
		return ret.toString();
	}

}
