/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.tiendaenlinea.integracion.dto;

import edu.co.sena.tiendaenlinea.integracion.dao.*;
import edu.co.sena.tiendaenlinea.integracion.factory.*;
import edu.co.sena.tiendaenlinea.integracion.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class DomicilioProveedor implements Serializable
{
	/** 
	 * This attribute maps to the column Proveedor_idProveedor in the domicilio_proveedor table.
	 */
	protected String proveedorIdproveedor;

	/** 
	 * This attribute maps to the column Proveedor_tipoDeIdentificacion in the domicilio_proveedor table.
	 */
	protected String proveedorTipodeidentificacion;

	/** 
	 * This attribute maps to the column telefono in the domicilio_proveedor table.
	 */
	protected String telefono;

	/** 
	 * This attribute maps to the column direccion in the domicilio_proveedor table.
	 */
	protected String direccion;

	/** 
	 * This attribute maps to the column barrio in the domicilio_proveedor table.
	 */
	protected String barrio;

	/** 
	 * This attribute maps to the column localidad in the domicilio_proveedor table.
	 */
	protected String localidad;

	/** 
	 * This attribute maps to the column Municipio_idMunicipio in the domicilio_proveedor table.
	 */
	protected String municipioIdmunicipio;

	/**
	 * Method 'DomicilioProveedor'
	 * 
	 */
	public DomicilioProveedor()
	{
	}

	/**
	 * Method 'getProveedorIdproveedor'
	 * 
	 * @return String
	 */
	public String getProveedorIdproveedor()
	{
		return proveedorIdproveedor;
	}

	/**
	 * Method 'setProveedorIdproveedor'
	 * 
	 * @param proveedorIdproveedor
	 */
	public void setProveedorIdproveedor(String proveedorIdproveedor)
	{
		this.proveedorIdproveedor = proveedorIdproveedor;
	}

	/**
	 * Method 'getProveedorTipodeidentificacion'
	 * 
	 * @return String
	 */
	public String getProveedorTipodeidentificacion()
	{
		return proveedorTipodeidentificacion;
	}

	/**
	 * Method 'setProveedorTipodeidentificacion'
	 * 
	 * @param proveedorTipodeidentificacion
	 */
	public void setProveedorTipodeidentificacion(String proveedorTipodeidentificacion)
	{
		this.proveedorTipodeidentificacion = proveedorTipodeidentificacion;
	}

	/**
	 * Method 'getTelefono'
	 * 
	 * @return String
	 */
	public String getTelefono()
	{
		return telefono;
	}

	/**
	 * Method 'setTelefono'
	 * 
	 * @param telefono
	 */
	public void setTelefono(String telefono)
	{
		this.telefono = telefono;
	}

	/**
	 * Method 'getDireccion'
	 * 
	 * @return String
	 */
	public String getDireccion()
	{
		return direccion;
	}

	/**
	 * Method 'setDireccion'
	 * 
	 * @param direccion
	 */
	public void setDireccion(String direccion)
	{
		this.direccion = direccion;
	}

	/**
	 * Method 'getBarrio'
	 * 
	 * @return String
	 */
	public String getBarrio()
	{
		return barrio;
	}

	/**
	 * Method 'setBarrio'
	 * 
	 * @param barrio
	 */
	public void setBarrio(String barrio)
	{
		this.barrio = barrio;
	}

	/**
	 * Method 'getLocalidad'
	 * 
	 * @return String
	 */
	public String getLocalidad()
	{
		return localidad;
	}

	/**
	 * Method 'setLocalidad'
	 * 
	 * @param localidad
	 */
	public void setLocalidad(String localidad)
	{
		this.localidad = localidad;
	}

	/**
	 * Method 'getMunicipioIdmunicipio'
	 * 
	 * @return String
	 */
	public String getMunicipioIdmunicipio()
	{
		return municipioIdmunicipio;
	}

	/**
	 * Method 'setMunicipioIdmunicipio'
	 * 
	 * @param municipioIdmunicipio
	 */
	public void setMunicipioIdmunicipio(String municipioIdmunicipio)
	{
		this.municipioIdmunicipio = municipioIdmunicipio;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof DomicilioProveedor)) {
			return false;
		}
		
		final DomicilioProveedor _cast = (DomicilioProveedor) _other;
		if (proveedorIdproveedor == null ? _cast.proveedorIdproveedor != proveedorIdproveedor : !proveedorIdproveedor.equals( _cast.proveedorIdproveedor )) {
			return false;
		}
		
		if (proveedorTipodeidentificacion == null ? _cast.proveedorTipodeidentificacion != proveedorTipodeidentificacion : !proveedorTipodeidentificacion.equals( _cast.proveedorTipodeidentificacion )) {
			return false;
		}
		
		if (telefono == null ? _cast.telefono != telefono : !telefono.equals( _cast.telefono )) {
			return false;
		}
		
		if (direccion == null ? _cast.direccion != direccion : !direccion.equals( _cast.direccion )) {
			return false;
		}
		
		if (barrio == null ? _cast.barrio != barrio : !barrio.equals( _cast.barrio )) {
			return false;
		}
		
		if (localidad == null ? _cast.localidad != localidad : !localidad.equals( _cast.localidad )) {
			return false;
		}
		
		if (municipioIdmunicipio == null ? _cast.municipioIdmunicipio != municipioIdmunicipio : !municipioIdmunicipio.equals( _cast.municipioIdmunicipio )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (proveedorIdproveedor != null) {
			_hashCode = 29 * _hashCode + proveedorIdproveedor.hashCode();
		}
		
		if (proveedorTipodeidentificacion != null) {
			_hashCode = 29 * _hashCode + proveedorTipodeidentificacion.hashCode();
		}
		
		if (telefono != null) {
			_hashCode = 29 * _hashCode + telefono.hashCode();
		}
		
		if (direccion != null) {
			_hashCode = 29 * _hashCode + direccion.hashCode();
		}
		
		if (barrio != null) {
			_hashCode = 29 * _hashCode + barrio.hashCode();
		}
		
		if (localidad != null) {
			_hashCode = 29 * _hashCode + localidad.hashCode();
		}
		
		if (municipioIdmunicipio != null) {
			_hashCode = 29 * _hashCode + municipioIdmunicipio.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return DomicilioProveedorPk
	 */
	public DomicilioProveedorPk createPk()
	{
		return new DomicilioProveedorPk(proveedorIdproveedor, proveedorTipodeidentificacion);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.tiendaenlinea.integracion.dto.DomicilioProveedor: " );
		ret.append( "proveedorIdproveedor=" + proveedorIdproveedor );
		ret.append( ", proveedorTipodeidentificacion=" + proveedorTipodeidentificacion );
		ret.append( ", telefono=" + telefono );
		ret.append( ", direccion=" + direccion );
		ret.append( ", barrio=" + barrio );
		ret.append( ", localidad=" + localidad );
		ret.append( ", municipioIdmunicipio=" + municipioIdmunicipio );
		return ret.toString();
	}

}
