/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.tiendaenlinea.integracion.dto;

import edu.co.sena.tiendaenlinea.integracion.dao.*;
import edu.co.sena.tiendaenlinea.integracion.factory.*;
import edu.co.sena.tiendaenlinea.integracion.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class DomicilioCuenta implements Serializable
{
	/** 
	 * This attribute maps to the column Cuenta_tipoDocumento in the domicilio_cuenta table.
	 */
	protected String cuentaTipodocumento;

	/** 
	 * This attribute maps to the column Cuenta_numeroDocumento in the domicilio_cuenta table.
	 */
	protected String cuentaNumerodocumento;

	/** 
	 * This attribute maps to the column telefono in the domicilio_cuenta table.
	 */
	protected String telefono;

	/** 
	 * This attribute maps to the column direccion in the domicilio_cuenta table.
	 */
	protected String direccion;

	/** 
	 * This attribute maps to the column barrio in the domicilio_cuenta table.
	 */
	protected String barrio;

	/** 
	 * This attribute maps to the column localidad in the domicilio_cuenta table.
	 */
	protected String localidad;

	/** 
	 * This attribute maps to the column Municipio_idMunicipio in the domicilio_cuenta table.
	 */
	protected String municipioIdmunicipio;

	/**
	 * Method 'DomicilioCuenta'
	 * 
	 */
	public DomicilioCuenta()
	{
	}

	/**
	 * Method 'getCuentaTipodocumento'
	 * 
	 * @return String
	 */
	public String getCuentaTipodocumento()
	{
		return cuentaTipodocumento;
	}

	/**
	 * Method 'setCuentaTipodocumento'
	 * 
	 * @param cuentaTipodocumento
	 */
	public void setCuentaTipodocumento(String cuentaTipodocumento)
	{
		this.cuentaTipodocumento = cuentaTipodocumento;
	}

	/**
	 * Method 'getCuentaNumerodocumento'
	 * 
	 * @return String
	 */
	public String getCuentaNumerodocumento()
	{
		return cuentaNumerodocumento;
	}

	/**
	 * Method 'setCuentaNumerodocumento'
	 * 
	 * @param cuentaNumerodocumento
	 */
	public void setCuentaNumerodocumento(String cuentaNumerodocumento)
	{
		this.cuentaNumerodocumento = cuentaNumerodocumento;
	}

	/**
	 * Method 'getTelefono'
	 * 
	 * @return String
	 */
	public String getTelefono()
	{
		return telefono;
	}

	/**
	 * Method 'setTelefono'
	 * 
	 * @param telefono
	 */
	public void setTelefono(String telefono)
	{
		this.telefono = telefono;
	}

	/**
	 * Method 'getDireccion'
	 * 
	 * @return String
	 */
	public String getDireccion()
	{
		return direccion;
	}

	/**
	 * Method 'setDireccion'
	 * 
	 * @param direccion
	 */
	public void setDireccion(String direccion)
	{
		this.direccion = direccion;
	}

	/**
	 * Method 'getBarrio'
	 * 
	 * @return String
	 */
	public String getBarrio()
	{
		return barrio;
	}

	/**
	 * Method 'setBarrio'
	 * 
	 * @param barrio
	 */
	public void setBarrio(String barrio)
	{
		this.barrio = barrio;
	}

	/**
	 * Method 'getLocalidad'
	 * 
	 * @return String
	 */
	public String getLocalidad()
	{
		return localidad;
	}

	/**
	 * Method 'setLocalidad'
	 * 
	 * @param localidad
	 */
	public void setLocalidad(String localidad)
	{
		this.localidad = localidad;
	}

	/**
	 * Method 'getMunicipioIdmunicipio'
	 * 
	 * @return String
	 */
	public String getMunicipioIdmunicipio()
	{
		return municipioIdmunicipio;
	}

	/**
	 * Method 'setMunicipioIdmunicipio'
	 * 
	 * @param municipioIdmunicipio
	 */
	public void setMunicipioIdmunicipio(String municipioIdmunicipio)
	{
		this.municipioIdmunicipio = municipioIdmunicipio;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof DomicilioCuenta)) {
			return false;
		}
		
		final DomicilioCuenta _cast = (DomicilioCuenta) _other;
		if (cuentaTipodocumento == null ? _cast.cuentaTipodocumento != cuentaTipodocumento : !cuentaTipodocumento.equals( _cast.cuentaTipodocumento )) {
			return false;
		}
		
		if (cuentaNumerodocumento == null ? _cast.cuentaNumerodocumento != cuentaNumerodocumento : !cuentaNumerodocumento.equals( _cast.cuentaNumerodocumento )) {
			return false;
		}
		
		if (telefono == null ? _cast.telefono != telefono : !telefono.equals( _cast.telefono )) {
			return false;
		}
		
		if (direccion == null ? _cast.direccion != direccion : !direccion.equals( _cast.direccion )) {
			return false;
		}
		
		if (barrio == null ? _cast.barrio != barrio : !barrio.equals( _cast.barrio )) {
			return false;
		}
		
		if (localidad == null ? _cast.localidad != localidad : !localidad.equals( _cast.localidad )) {
			return false;
		}
		
		if (municipioIdmunicipio == null ? _cast.municipioIdmunicipio != municipioIdmunicipio : !municipioIdmunicipio.equals( _cast.municipioIdmunicipio )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (cuentaTipodocumento != null) {
			_hashCode = 29 * _hashCode + cuentaTipodocumento.hashCode();
		}
		
		if (cuentaNumerodocumento != null) {
			_hashCode = 29 * _hashCode + cuentaNumerodocumento.hashCode();
		}
		
		if (telefono != null) {
			_hashCode = 29 * _hashCode + telefono.hashCode();
		}
		
		if (direccion != null) {
			_hashCode = 29 * _hashCode + direccion.hashCode();
		}
		
		if (barrio != null) {
			_hashCode = 29 * _hashCode + barrio.hashCode();
		}
		
		if (localidad != null) {
			_hashCode = 29 * _hashCode + localidad.hashCode();
		}
		
		if (municipioIdmunicipio != null) {
			_hashCode = 29 * _hashCode + municipioIdmunicipio.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return DomicilioCuentaPk
	 */
	public DomicilioCuentaPk createPk()
	{
		return new DomicilioCuentaPk(cuentaTipodocumento, cuentaNumerodocumento);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.tiendaenlinea.integracion.dto.DomicilioCuenta: " );
		ret.append( "cuentaTipodocumento=" + cuentaTipodocumento );
		ret.append( ", cuentaNumerodocumento=" + cuentaNumerodocumento );
		ret.append( ", telefono=" + telefono );
		ret.append( ", direccion=" + direccion );
		ret.append( ", barrio=" + barrio );
		ret.append( ", localidad=" + localidad );
		ret.append( ", municipioIdmunicipio=" + municipioIdmunicipio );
		return ret.toString();
	}

}
