/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.tiendaenlinea.integracion.dto;

import edu.co.sena.tiendaenlinea.integracion.dao.*;
import edu.co.sena.tiendaenlinea.integracion.factory.*;
import edu.co.sena.tiendaenlinea.integracion.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Inventario implements Serializable
{
	/** 
	 * This attribute maps to the column idInventario in the inventario table.
	 */
	protected int idInventario;

	/** 
	 * This attribute maps to the column fecha in the inventario table.
	 */
	protected Date fecha;

	/** 
	 * This attribute maps to the column cantidad in the inventario table.
	 */
	protected int cantidad;

	/** 
	 * This attribute maps to the column Producto_idProducto in the inventario table.
	 */
	protected String productoIdproducto;

	/** 
	 * This attribute maps to the column Proveedor_idProveedor in the inventario table.
	 */
	protected String proveedorIdproveedor;

	/** 
	 * This attribute maps to the column Proveedor_tipoDeIdentificacion in the inventario table.
	 */
	protected String proveedorTipodeidentificacion;

	/**
	 * Method 'Inventario'
	 * 
	 */
	public Inventario()
	{
	}

	/**
	 * Method 'getIdInventario'
	 * 
	 * @return int
	 */
	public int getIdInventario()
	{
		return idInventario;
	}

	/**
	 * Method 'setIdInventario'
	 * 
	 * @param idInventario
	 */
	public void setIdInventario(int idInventario)
	{
		this.idInventario = idInventario;
	}

	/**
	 * Method 'getFecha'
	 * 
	 * @return Date
	 */
	public Date getFecha()
	{
		return fecha;
	}

	/**
	 * Method 'setFecha'
	 * 
	 * @param fecha
	 */
	public void setFecha(Date fecha)
	{
		this.fecha = fecha;
	}

	/**
	 * Method 'getCantidad'
	 * 
	 * @return int
	 */
	public int getCantidad()
	{
		return cantidad;
	}

	/**
	 * Method 'setCantidad'
	 * 
	 * @param cantidad
	 */
	public void setCantidad(int cantidad)
	{
		this.cantidad = cantidad;
	}

	/**
	 * Method 'getProductoIdproducto'
	 * 
	 * @return String
	 */
	public String getProductoIdproducto()
	{
		return productoIdproducto;
	}

	/**
	 * Method 'setProductoIdproducto'
	 * 
	 * @param productoIdproducto
	 */
	public void setProductoIdproducto(String productoIdproducto)
	{
		this.productoIdproducto = productoIdproducto;
	}

	/**
	 * Method 'getProveedorIdproveedor'
	 * 
	 * @return String
	 */
	public String getProveedorIdproveedor()
	{
		return proveedorIdproveedor;
	}

	/**
	 * Method 'setProveedorIdproveedor'
	 * 
	 * @param proveedorIdproveedor
	 */
	public void setProveedorIdproveedor(String proveedorIdproveedor)
	{
		this.proveedorIdproveedor = proveedorIdproveedor;
	}

	/**
	 * Method 'getProveedorTipodeidentificacion'
	 * 
	 * @return String
	 */
	public String getProveedorTipodeidentificacion()
	{
		return proveedorTipodeidentificacion;
	}

	/**
	 * Method 'setProveedorTipodeidentificacion'
	 * 
	 * @param proveedorTipodeidentificacion
	 */
	public void setProveedorTipodeidentificacion(String proveedorTipodeidentificacion)
	{
		this.proveedorTipodeidentificacion = proveedorTipodeidentificacion;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Inventario)) {
			return false;
		}
		
		final Inventario _cast = (Inventario) _other;
		if (idInventario != _cast.idInventario) {
			return false;
		}
		
		if (fecha == null ? _cast.fecha != fecha : !fecha.equals( _cast.fecha )) {
			return false;
		}
		
		if (cantidad != _cast.cantidad) {
			return false;
		}
		
		if (productoIdproducto == null ? _cast.productoIdproducto != productoIdproducto : !productoIdproducto.equals( _cast.productoIdproducto )) {
			return false;
		}
		
		if (proveedorIdproveedor == null ? _cast.proveedorIdproveedor != proveedorIdproveedor : !proveedorIdproveedor.equals( _cast.proveedorIdproveedor )) {
			return false;
		}
		
		if (proveedorTipodeidentificacion == null ? _cast.proveedorTipodeidentificacion != proveedorTipodeidentificacion : !proveedorTipodeidentificacion.equals( _cast.proveedorTipodeidentificacion )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idInventario;
		if (fecha != null) {
			_hashCode = 29 * _hashCode + fecha.hashCode();
		}
		
		_hashCode = 29 * _hashCode + cantidad;
		if (productoIdproducto != null) {
			_hashCode = 29 * _hashCode + productoIdproducto.hashCode();
		}
		
		if (proveedorIdproveedor != null) {
			_hashCode = 29 * _hashCode + proveedorIdproveedor.hashCode();
		}
		
		if (proveedorTipodeidentificacion != null) {
			_hashCode = 29 * _hashCode + proveedorTipodeidentificacion.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return InventarioPk
	 */
	public InventarioPk createPk()
	{
		return new InventarioPk(idInventario, productoIdproducto, proveedorIdproveedor, proveedorTipodeidentificacion);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.tiendaenlinea.integracion.dto.Inventario: " );
		ret.append( "idInventario=" + idInventario );
		ret.append( ", fecha=" + fecha );
		ret.append( ", cantidad=" + cantidad );
		ret.append( ", productoIdproducto=" + productoIdproducto );
		ret.append( ", proveedorIdproveedor=" + proveedorIdproveedor );
		ret.append( ", proveedorTipodeidentificacion=" + proveedorTipodeidentificacion );
		return ret.toString();
	}

}
