/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.tiendaenlinea.integracion.dto;

import edu.co.sena.tiendaenlinea.integracion.dao.*;
import edu.co.sena.tiendaenlinea.integracion.factory.*;
import edu.co.sena.tiendaenlinea.integracion.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Item implements Serializable
{
	/** 
	 * This attribute maps to the column Producto_idProducto in the item table.
	 */
	protected String productoIdproducto;

	/** 
	 * This attribute maps to the column Pedido_Factura_idFactura in the item table.
	 */
	protected int pedidoFacturaIdfactura;

	/** 
	 * This attribute maps to the column cantidad in the item table.
	 */
	protected int cantidad;

	/** 
	 * This attribute maps to the column costoUnitario in the item table.
	 */
	protected float costoUnitario;

	/** 
	 * This attribute maps to the column costoTotal in the item table.
	 */
	protected float costoTotal;

	/**
	 * Method 'Item'
	 * 
	 */
	public Item()
	{
	}

	/**
	 * Method 'getProductoIdproducto'
	 * 
	 * @return String
	 */
	public String getProductoIdproducto()
	{
		return productoIdproducto;
	}

	/**
	 * Method 'setProductoIdproducto'
	 * 
	 * @param productoIdproducto
	 */
	public void setProductoIdproducto(String productoIdproducto)
	{
		this.productoIdproducto = productoIdproducto;
	}

	/**
	 * Method 'getPedidoFacturaIdfactura'
	 * 
	 * @return int
	 */
	public int getPedidoFacturaIdfactura()
	{
		return pedidoFacturaIdfactura;
	}

	/**
	 * Method 'setPedidoFacturaIdfactura'
	 * 
	 * @param pedidoFacturaIdfactura
	 */
	public void setPedidoFacturaIdfactura(int pedidoFacturaIdfactura)
	{
		this.pedidoFacturaIdfactura = pedidoFacturaIdfactura;
	}

	/**
	 * Method 'getCantidad'
	 * 
	 * @return int
	 */
	public int getCantidad()
	{
		return cantidad;
	}

	/**
	 * Method 'setCantidad'
	 * 
	 * @param cantidad
	 */
	public void setCantidad(int cantidad)
	{
		this.cantidad = cantidad;
	}

	/**
	 * Method 'getCostoUnitario'
	 * 
	 * @return float
	 */
	public float getCostoUnitario()
	{
		return costoUnitario;
	}

	/**
	 * Method 'setCostoUnitario'
	 * 
	 * @param costoUnitario
	 */
	public void setCostoUnitario(float costoUnitario)
	{
		this.costoUnitario = costoUnitario;
	}

	/**
	 * Method 'getCostoTotal'
	 * 
	 * @return float
	 */
	public float getCostoTotal()
	{
		return costoTotal;
	}

	/**
	 * Method 'setCostoTotal'
	 * 
	 * @param costoTotal
	 */
	public void setCostoTotal(float costoTotal)
	{
		this.costoTotal = costoTotal;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Item)) {
			return false;
		}
		
		final Item _cast = (Item) _other;
		if (productoIdproducto == null ? _cast.productoIdproducto != productoIdproducto : !productoIdproducto.equals( _cast.productoIdproducto )) {
			return false;
		}
		
		if (pedidoFacturaIdfactura != _cast.pedidoFacturaIdfactura) {
			return false;
		}
		
		if (cantidad != _cast.cantidad) {
			return false;
		}
		
		if (costoUnitario != _cast.costoUnitario) {
			return false;
		}
		
		if (costoTotal != _cast.costoTotal) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (productoIdproducto != null) {
			_hashCode = 29 * _hashCode + productoIdproducto.hashCode();
		}
		
		_hashCode = 29 * _hashCode + pedidoFacturaIdfactura;
		_hashCode = 29 * _hashCode + cantidad;
		_hashCode = 29 * _hashCode + Float.floatToIntBits(costoUnitario);
		_hashCode = 29 * _hashCode + Float.floatToIntBits(costoTotal);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ItemPk
	 */
	public ItemPk createPk()
	{
		return new ItemPk(productoIdproducto, pedidoFacturaIdfactura);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.tiendaenlinea.integracion.dto.Item: " );
		ret.append( "productoIdproducto=" + productoIdproducto );
		ret.append( ", pedidoFacturaIdfactura=" + pedidoFacturaIdfactura );
		ret.append( ", cantidad=" + cantidad );
		ret.append( ", costoUnitario=" + costoUnitario );
		ret.append( ", costoTotal=" + costoTotal );
		return ret.toString();
	}

}
