/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.tiendaenlinea.integracion.dto;

import edu.co.sena.tiendaenlinea.integracion.dao.*;
import edu.co.sena.tiendaenlinea.integracion.factory.*;
import edu.co.sena.tiendaenlinea.integracion.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Proveedor implements Serializable
{
	/** 
	 * This attribute maps to the column idProveedor in the proveedor table.
	 */
	protected String idProveedor;

	/** 
	 * This attribute maps to the column tipoDeIdentificacion in the proveedor table.
	 */
	protected String tipoDeIdentificacion;

	/** 
	 * This attribute maps to the column nombre in the proveedor table.
	 */
	protected String nombre;

	/** 
	 * This attribute maps to the column telefono in the proveedor table.
	 */
	protected String telefono;

	/** 
	 * This attribute maps to the column email in the proveedor table.
	 */
	protected String email;

	/**
	 * Method 'Proveedor'
	 * 
	 */
	public Proveedor()
	{
	}

	/**
	 * Method 'getIdProveedor'
	 * 
	 * @return String
	 */
	public String getIdProveedor()
	{
		return idProveedor;
	}

	/**
	 * Method 'setIdProveedor'
	 * 
	 * @param idProveedor
	 */
	public void setIdProveedor(String idProveedor)
	{
		this.idProveedor = idProveedor;
	}

	/**
	 * Method 'getTipoDeIdentificacion'
	 * 
	 * @return String
	 */
	public String getTipoDeIdentificacion()
	{
		return tipoDeIdentificacion;
	}

	/**
	 * Method 'setTipoDeIdentificacion'
	 * 
	 * @param tipoDeIdentificacion
	 */
	public void setTipoDeIdentificacion(String tipoDeIdentificacion)
	{
		this.tipoDeIdentificacion = tipoDeIdentificacion;
	}

	/**
	 * Method 'getNombre'
	 * 
	 * @return String
	 */
	public String getNombre()
	{
		return nombre;
	}

	/**
	 * Method 'setNombre'
	 * 
	 * @param nombre
	 */
	public void setNombre(String nombre)
	{
		this.nombre = nombre;
	}

	/**
	 * Method 'getTelefono'
	 * 
	 * @return String
	 */
	public String getTelefono()
	{
		return telefono;
	}

	/**
	 * Method 'setTelefono'
	 * 
	 * @param telefono
	 */
	public void setTelefono(String telefono)
	{
		this.telefono = telefono;
	}

	/**
	 * Method 'getEmail'
	 * 
	 * @return String
	 */
	public String getEmail()
	{
		return email;
	}

	/**
	 * Method 'setEmail'
	 * 
	 * @param email
	 */
	public void setEmail(String email)
	{
		this.email = email;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Proveedor)) {
			return false;
		}
		
		final Proveedor _cast = (Proveedor) _other;
		if (idProveedor == null ? _cast.idProveedor != idProveedor : !idProveedor.equals( _cast.idProveedor )) {
			return false;
		}
		
		if (tipoDeIdentificacion == null ? _cast.tipoDeIdentificacion != tipoDeIdentificacion : !tipoDeIdentificacion.equals( _cast.tipoDeIdentificacion )) {
			return false;
		}
		
		if (nombre == null ? _cast.nombre != nombre : !nombre.equals( _cast.nombre )) {
			return false;
		}
		
		if (telefono == null ? _cast.telefono != telefono : !telefono.equals( _cast.telefono )) {
			return false;
		}
		
		if (email == null ? _cast.email != email : !email.equals( _cast.email )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idProveedor != null) {
			_hashCode = 29 * _hashCode + idProveedor.hashCode();
		}
		
		if (tipoDeIdentificacion != null) {
			_hashCode = 29 * _hashCode + tipoDeIdentificacion.hashCode();
		}
		
		if (nombre != null) {
			_hashCode = 29 * _hashCode + nombre.hashCode();
		}
		
		if (telefono != null) {
			_hashCode = 29 * _hashCode + telefono.hashCode();
		}
		
		if (email != null) {
			_hashCode = 29 * _hashCode + email.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ProveedorPk
	 */
	public ProveedorPk createPk()
	{
		return new ProveedorPk(idProveedor, tipoDeIdentificacion);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.tiendaenlinea.integracion.dto.Proveedor: " );
		ret.append( "idProveedor=" + idProveedor );
		ret.append( ", tipoDeIdentificacion=" + tipoDeIdentificacion );
		ret.append( ", nombre=" + nombre );
		ret.append( ", telefono=" + telefono );
		ret.append( ", email=" + email );
		return ret.toString();
	}

}
