/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.tiendaenlinea.integracion.jdbc;

import edu.co.sena.tiendaenlinea.integracion.dao.*;
import edu.co.sena.tiendaenlinea.integracion.factory.*;
import edu.co.sena.tiendaenlinea.integracion.dto.*;
import edu.co.sena.tiendaenlinea.integracion.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import org.apache.log4j.Logger;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class CuentaDaoImpl extends AbstractDAO implements CuentaDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	protected static final Logger logger = Logger.getLogger( CuentaDaoImpl.class );

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT tipoDocumento, numeroDocumento, primerNombre, segundoNombre, primerApellido, segundoApellido, contrasena, email, Usuario_idUsuario FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( tipoDocumento, numeroDocumento, primerNombre, segundoNombre, primerApellido, segundoApellido, contrasena, email, Usuario_idUsuario ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET tipoDocumento = ?, numeroDocumento = ?, primerNombre = ?, segundoNombre = ?, primerApellido = ?, segundoApellido = ?, contrasena = ?, email = ?, Usuario_idUsuario = ? WHERE tipoDocumento = ? AND numeroDocumento = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE tipoDocumento = ? AND numeroDocumento = ?";

	/** 
	 * Index of column tipoDocumento
	 */
	protected static final int COLUMN_TIPO_DOCUMENTO = 1;

	/** 
	 * Index of column numeroDocumento
	 */
	protected static final int COLUMN_NUMERO_DOCUMENTO = 2;

	/** 
	 * Index of column primerNombre
	 */
	protected static final int COLUMN_PRIMER_NOMBRE = 3;

	/** 
	 * Index of column segundoNombre
	 */
	protected static final int COLUMN_SEGUNDO_NOMBRE = 4;

	/** 
	 * Index of column primerApellido
	 */
	protected static final int COLUMN_PRIMER_APELLIDO = 5;

	/** 
	 * Index of column segundoApellido
	 */
	protected static final int COLUMN_SEGUNDO_APELLIDO = 6;

	/** 
	 * Index of column contrasena
	 */
	protected static final int COLUMN_CONTRASENA = 7;

	/** 
	 * Index of column email
	 */
	protected static final int COLUMN_EMAIL = 8;

	/** 
	 * Index of column Usuario_idUsuario
	 */
	protected static final int COLUMN_USUARIO_IDUSUARIO = 9;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 9;

	/** 
	 * Index of primary-key column tipoDocumento
	 */
	protected static final int PK_COLUMN_TIPO_DOCUMENTO = 1;

	/** 
	 * Index of primary-key column numeroDocumento
	 */
	protected static final int PK_COLUMN_NUMERO_DOCUMENTO = 2;

	/** 
	 * Inserts a new row in the cuenta table.
	 */
	public CuentaPk insert(Cuenta dto) throws CuentaDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			StringBuffer values = new StringBuffer();
			sql.append( "INSERT INTO " + getTableName() + " (" );
			int modifiedCount = 0;
			if (dto.isTipoDocumentoModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "tipoDocumento" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isNumeroDocumentoModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "numeroDocumento" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isPrimerNombreModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "primerNombre" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isSegundoNombreModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "segundoNombre" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isPrimerApellidoModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "primerApellido" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isSegundoApellidoModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "segundoApellido" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isContrasenaModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "contrasena" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isEmailModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "email" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isUsuarioIdusuarioModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "Usuario_idUsuario" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (modifiedCount==0) {
				// nothing to insert
				throw new IllegalStateException( "Nothing to insert" );
			}
		
			sql.append( ") VALUES (" );
			sql.append( values );
			sql.append( ")" );
			stmt = conn.prepareStatement( sql.toString() );
			int index = 1;
			if (dto.isTipoDocumentoModified()) {
				stmt.setString( index++, dto.getTipoDocumento() );
			}
		
			if (dto.isNumeroDocumentoModified()) {
				stmt.setString( index++, dto.getNumeroDocumento() );
			}
		
			if (dto.isPrimerNombreModified()) {
				stmt.setString( index++, dto.getPrimerNombre() );
			}
		
			if (dto.isSegundoNombreModified()) {
				stmt.setString( index++, dto.getSegundoNombre() );
			}
		
			if (dto.isPrimerApellidoModified()) {
				stmt.setString( index++, dto.getPrimerApellido() );
			}
		
			if (dto.isSegundoApellidoModified()) {
				stmt.setString( index++, dto.getSegundoApellido() );
			}
		
			if (dto.isContrasenaModified()) {
				stmt.setString( index++, dto.getContrasena() );
			}
		
			if (dto.isEmailModified()) {
				stmt.setString( index++, dto.getEmail() );
			}
		
			if (dto.isUsuarioIdusuarioModified()) {
				stmt.setString( index++, dto.getUsuarioIdusuario() );
			}
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + sql.toString() + " with values: " + dto);
			}
		
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			if (logger.isDebugEnabled()) {
				logger.debug( rows + " rows affected (" + (t2-t1) + " ms)");
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new CuentaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the cuenta table.
	 */
	public void update(CuentaPk pk, Cuenta dto) throws CuentaDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			sql.append( "UPDATE " + getTableName() + " SET " );
			boolean modified = false;
			if (dto.isTipoDocumentoModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "tipoDocumento=?" );
				modified=true;
			}
		
			if (dto.isNumeroDocumentoModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "numeroDocumento=?" );
				modified=true;
			}
		
			if (dto.isPrimerNombreModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "primerNombre=?" );
				modified=true;
			}
		
			if (dto.isSegundoNombreModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "segundoNombre=?" );
				modified=true;
			}
		
			if (dto.isPrimerApellidoModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "primerApellido=?" );
				modified=true;
			}
		
			if (dto.isSegundoApellidoModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "segundoApellido=?" );
				modified=true;
			}
		
			if (dto.isContrasenaModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "contrasena=?" );
				modified=true;
			}
		
			if (dto.isEmailModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "email=?" );
				modified=true;
			}
		
			if (dto.isUsuarioIdusuarioModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "Usuario_idUsuario=?" );
				modified=true;
			}
		
			if (!modified) {
				// nothing to update
				return;
			}
		
			sql.append( " WHERE tipoDocumento=? AND numeroDocumento=?" );
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + sql.toString() + " with values: " + dto);
			}
		
			stmt = conn.prepareStatement( sql.toString() );
			int index = 1;
			if (dto.isTipoDocumentoModified()) {
				stmt.setString( index++, dto.getTipoDocumento() );
			}
		
			if (dto.isNumeroDocumentoModified()) {
				stmt.setString( index++, dto.getNumeroDocumento() );
			}
		
			if (dto.isPrimerNombreModified()) {
				stmt.setString( index++, dto.getPrimerNombre() );
			}
		
			if (dto.isSegundoNombreModified()) {
				stmt.setString( index++, dto.getSegundoNombre() );
			}
		
			if (dto.isPrimerApellidoModified()) {
				stmt.setString( index++, dto.getPrimerApellido() );
			}
		
			if (dto.isSegundoApellidoModified()) {
				stmt.setString( index++, dto.getSegundoApellido() );
			}
		
			if (dto.isContrasenaModified()) {
				stmt.setString( index++, dto.getContrasena() );
			}
		
			if (dto.isEmailModified()) {
				stmt.setString( index++, dto.getEmail() );
			}
		
			if (dto.isUsuarioIdusuarioModified()) {
				stmt.setString( index++, dto.getUsuarioIdusuario() );
			}
		
			stmt.setString( index++, pk.getTipoDocumento() );
			stmt.setString( index++, pk.getNumeroDocumento() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			if (logger.isDebugEnabled()) {
				logger.debug( rows + " rows affected (" + (t2-t1) + " ms)");
			}
		
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new CuentaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the cuenta table.
	 */
	public void delete(CuentaPk pk) throws CuentaDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + SQL_DELETE + " with PK: " + pk);
			}
		
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setString( 1, pk.getTipoDocumento() );
			stmt.setString( 2, pk.getNumeroDocumento() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			if (logger.isDebugEnabled()) {
				logger.debug( rows + " rows affected (" + (t2-t1) + " ms)");
			}
		
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new CuentaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the cuenta table that matches the specified primary-key value.
	 */
	public Cuenta findByPrimaryKey(CuentaPk pk) throws CuentaDaoException
	{
		return findByPrimaryKey( pk.getTipoDocumento(), pk.getNumeroDocumento() );
	}

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'tipoDocumento = :tipoDocumento AND numeroDocumento = :numeroDocumento'.
	 */
	public Cuenta findByPrimaryKey(String tipoDocumento, String numeroDocumento) throws CuentaDaoException
	{
		Cuenta ret[] = findByDynamicSelect( SQL_SELECT + " WHERE tipoDocumento = ? AND numeroDocumento = ?", new Object[] { tipoDocumento, numeroDocumento } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the cuenta table that match the criteria ''.
	 */
	public Cuenta[] findAll() throws CuentaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY tipoDocumento, numeroDocumento", null );
	}

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'Usuario_idUsuario = :usuarioIdusuario'.
	 */
	public Cuenta[] findByUsuario(String usuarioIdusuario) throws CuentaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Usuario_idUsuario = ?", new Object[] { usuarioIdusuario } );
	}

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'tipoDocumento = :tipoDocumento'.
	 */
	public Cuenta[] findWhereTipoDocumentoEquals(String tipoDocumento) throws CuentaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE tipoDocumento = ? ORDER BY tipoDocumento", new Object[] { tipoDocumento } );
	}

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'numeroDocumento = :numeroDocumento'.
	 */
	public Cuenta[] findWhereNumeroDocumentoEquals(String numeroDocumento) throws CuentaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE numeroDocumento = ? ORDER BY numeroDocumento", new Object[] { numeroDocumento } );
	}

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'primerNombre = :primerNombre'.
	 */
	public Cuenta[] findWherePrimerNombreEquals(String primerNombre) throws CuentaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE primerNombre = ? ORDER BY primerNombre", new Object[] { primerNombre } );
	}

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'segundoNombre = :segundoNombre'.
	 */
	public Cuenta[] findWhereSegundoNombreEquals(String segundoNombre) throws CuentaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE segundoNombre = ? ORDER BY segundoNombre", new Object[] { segundoNombre } );
	}

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'primerApellido = :primerApellido'.
	 */
	public Cuenta[] findWherePrimerApellidoEquals(String primerApellido) throws CuentaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE primerApellido = ? ORDER BY primerApellido", new Object[] { primerApellido } );
	}

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'segundoApellido = :segundoApellido'.
	 */
	public Cuenta[] findWhereSegundoApellidoEquals(String segundoApellido) throws CuentaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE segundoApellido = ? ORDER BY segundoApellido", new Object[] { segundoApellido } );
	}

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'contrasena = :contrasena'.
	 */
	public Cuenta[] findWhereContrasenaEquals(String contrasena) throws CuentaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE contrasena = ? ORDER BY contrasena", new Object[] { contrasena } );
	}

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'email = :email'.
	 */
	public Cuenta[] findWhereEmailEquals(String email) throws CuentaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE email = ? ORDER BY email", new Object[] { email } );
	}

	/** 
	 * Returns all rows from the cuenta table that match the criteria 'Usuario_idUsuario = :usuarioIdusuario'.
	 */
	public Cuenta[] findWhereUsuarioIdusuarioEquals(String usuarioIdusuario) throws CuentaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Usuario_idUsuario = ? ORDER BY Usuario_idUsuario", new Object[] { usuarioIdusuario } );
	}

	/**
	 * Method 'CuentaDaoImpl'
	 * 
	 */
	public CuentaDaoImpl()
	{
	}

	/**
	 * Method 'CuentaDaoImpl'
	 * 
	 * @param userConn
	 */
	public CuentaDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "tiendaenlinea.cuenta";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Cuenta fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Cuenta dto = new Cuenta();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Cuenta[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Cuenta dto = new Cuenta();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Cuenta ret[] = new Cuenta[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Cuenta dto, ResultSet rs) throws SQLException
	{
		dto.setTipoDocumento( rs.getString( COLUMN_TIPO_DOCUMENTO ) );
		dto.setNumeroDocumento( rs.getString( COLUMN_NUMERO_DOCUMENTO ) );
		dto.setPrimerNombre( rs.getString( COLUMN_PRIMER_NOMBRE ) );
		dto.setSegundoNombre( rs.getString( COLUMN_SEGUNDO_NOMBRE ) );
		dto.setPrimerApellido( rs.getString( COLUMN_PRIMER_APELLIDO ) );
		dto.setSegundoApellido( rs.getString( COLUMN_SEGUNDO_APELLIDO ) );
		dto.setContrasena( rs.getString( COLUMN_CONTRASENA ) );
		dto.setEmail( rs.getString( COLUMN_EMAIL ) );
		dto.setUsuarioIdusuario( rs.getString( COLUMN_USUARIO_IDUSUARIO ) );
		reset(dto);
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Cuenta dto)
	{
		dto.setTipoDocumentoModified( false );
		dto.setNumeroDocumentoModified( false );
		dto.setPrimerNombreModified( false );
		dto.setSegundoNombreModified( false );
		dto.setPrimerApellidoModified( false );
		dto.setSegundoApellidoModified( false );
		dto.setContrasenaModified( false );
		dto.setEmailModified( false );
		dto.setUsuarioIdusuarioModified( false );
	}

	/** 
	 * Returns all rows from the cuenta table that match the specified arbitrary SQL statement
	 */
	public Cuenta[] findByDynamicSelect(String sql, Object[] sqlParams) throws CuentaDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + SQL);
			}
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new CuentaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the cuenta table that match the specified arbitrary SQL statement
	 */
	public Cuenta[] findByDynamicWhere(String sql, Object[] sqlParams) throws CuentaDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + SQL);
			}
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new CuentaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
