/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.tiendaenlinea.integracion.jdbc;

import edu.co.sena.tiendaenlinea.integracion.dao.*;
import edu.co.sena.tiendaenlinea.integracion.factory.*;
import edu.co.sena.tiendaenlinea.integracion.dto.*;
import edu.co.sena.tiendaenlinea.integracion.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import org.apache.log4j.Logger;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class DomicilioProveedorDaoImpl extends AbstractDAO implements DomicilioProveedorDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	protected static final Logger logger = Logger.getLogger( DomicilioProveedorDaoImpl.class );

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT Proveedor_idProveedor, Proveedor_tipoDeIdentificacion, telefono, direccion, barrio, localidad, Municipio_idMunicipio FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( Proveedor_idProveedor, Proveedor_tipoDeIdentificacion, telefono, direccion, barrio, localidad, Municipio_idMunicipio ) VALUES ( ?, ?, ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET Proveedor_idProveedor = ?, Proveedor_tipoDeIdentificacion = ?, telefono = ?, direccion = ?, barrio = ?, localidad = ?, Municipio_idMunicipio = ? WHERE Proveedor_idProveedor = ? AND Proveedor_tipoDeIdentificacion = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE Proveedor_idProveedor = ? AND Proveedor_tipoDeIdentificacion = ?";

	/** 
	 * Index of column Proveedor_idProveedor
	 */
	protected static final int COLUMN_PROVEEDOR_IDPROVEEDOR = 1;

	/** 
	 * Index of column Proveedor_tipoDeIdentificacion
	 */
	protected static final int COLUMN_PROVEEDOR_TIPODEIDENTIFICACION = 2;

	/** 
	 * Index of column telefono
	 */
	protected static final int COLUMN_TELEFONO = 3;

	/** 
	 * Index of column direccion
	 */
	protected static final int COLUMN_DIRECCION = 4;

	/** 
	 * Index of column barrio
	 */
	protected static final int COLUMN_BARRIO = 5;

	/** 
	 * Index of column localidad
	 */
	protected static final int COLUMN_LOCALIDAD = 6;

	/** 
	 * Index of column Municipio_idMunicipio
	 */
	protected static final int COLUMN_MUNICIPIO_IDMUNICIPIO = 7;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 7;

	/** 
	 * Index of primary-key column Proveedor_idProveedor
	 */
	protected static final int PK_COLUMN_PROVEEDOR_IDPROVEEDOR = 1;

	/** 
	 * Index of primary-key column Proveedor_tipoDeIdentificacion
	 */
	protected static final int PK_COLUMN_PROVEEDOR_TIPODEIDENTIFICACION = 2;

	/** 
	 * Inserts a new row in the domicilio_proveedor table.
	 */
	public DomicilioProveedorPk insert(DomicilioProveedor dto) throws DomicilioProveedorDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			StringBuffer values = new StringBuffer();
			sql.append( "INSERT INTO " + getTableName() + " (" );
			int modifiedCount = 0;
			if (dto.isProveedorIdproveedorModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "Proveedor_idProveedor" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isProveedorTipodeidentificacionModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "Proveedor_tipoDeIdentificacion" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isTelefonoModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "telefono" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isDireccionModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "direccion" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isBarrioModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "barrio" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isLocalidadModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "localidad" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isMunicipioIdmunicipioModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "Municipio_idMunicipio" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (modifiedCount==0) {
				// nothing to insert
				throw new IllegalStateException( "Nothing to insert" );
			}
		
			sql.append( ") VALUES (" );
			sql.append( values );
			sql.append( ")" );
			stmt = conn.prepareStatement( sql.toString() );
			int index = 1;
			if (dto.isProveedorIdproveedorModified()) {
				stmt.setString( index++, dto.getProveedorIdproveedor() );
			}
		
			if (dto.isProveedorTipodeidentificacionModified()) {
				stmt.setString( index++, dto.getProveedorTipodeidentificacion() );
			}
		
			if (dto.isTelefonoModified()) {
				stmt.setString( index++, dto.getTelefono() );
			}
		
			if (dto.isDireccionModified()) {
				stmt.setString( index++, dto.getDireccion() );
			}
		
			if (dto.isBarrioModified()) {
				stmt.setString( index++, dto.getBarrio() );
			}
		
			if (dto.isLocalidadModified()) {
				stmt.setString( index++, dto.getLocalidad() );
			}
		
			if (dto.isMunicipioIdmunicipioModified()) {
				stmt.setString( index++, dto.getMunicipioIdmunicipio() );
			}
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + sql.toString() + " with values: " + dto);
			}
		
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			if (logger.isDebugEnabled()) {
				logger.debug( rows + " rows affected (" + (t2-t1) + " ms)");
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new DomicilioProveedorDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the domicilio_proveedor table.
	 */
	public void update(DomicilioProveedorPk pk, DomicilioProveedor dto) throws DomicilioProveedorDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			sql.append( "UPDATE " + getTableName() + " SET " );
			boolean modified = false;
			if (dto.isProveedorIdproveedorModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "Proveedor_idProveedor=?" );
				modified=true;
			}
		
			if (dto.isProveedorTipodeidentificacionModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "Proveedor_tipoDeIdentificacion=?" );
				modified=true;
			}
		
			if (dto.isTelefonoModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "telefono=?" );
				modified=true;
			}
		
			if (dto.isDireccionModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "direccion=?" );
				modified=true;
			}
		
			if (dto.isBarrioModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "barrio=?" );
				modified=true;
			}
		
			if (dto.isLocalidadModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "localidad=?" );
				modified=true;
			}
		
			if (dto.isMunicipioIdmunicipioModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "Municipio_idMunicipio=?" );
				modified=true;
			}
		
			if (!modified) {
				// nothing to update
				return;
			}
		
			sql.append( " WHERE Proveedor_idProveedor=? AND Proveedor_tipoDeIdentificacion=?" );
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + sql.toString() + " with values: " + dto);
			}
		
			stmt = conn.prepareStatement( sql.toString() );
			int index = 1;
			if (dto.isProveedorIdproveedorModified()) {
				stmt.setString( index++, dto.getProveedorIdproveedor() );
			}
		
			if (dto.isProveedorTipodeidentificacionModified()) {
				stmt.setString( index++, dto.getProveedorTipodeidentificacion() );
			}
		
			if (dto.isTelefonoModified()) {
				stmt.setString( index++, dto.getTelefono() );
			}
		
			if (dto.isDireccionModified()) {
				stmt.setString( index++, dto.getDireccion() );
			}
		
			if (dto.isBarrioModified()) {
				stmt.setString( index++, dto.getBarrio() );
			}
		
			if (dto.isLocalidadModified()) {
				stmt.setString( index++, dto.getLocalidad() );
			}
		
			if (dto.isMunicipioIdmunicipioModified()) {
				stmt.setString( index++, dto.getMunicipioIdmunicipio() );
			}
		
			stmt.setString( index++, pk.getProveedorIdproveedor() );
			stmt.setString( index++, pk.getProveedorTipodeidentificacion() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			if (logger.isDebugEnabled()) {
				logger.debug( rows + " rows affected (" + (t2-t1) + " ms)");
			}
		
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new DomicilioProveedorDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the domicilio_proveedor table.
	 */
	public void delete(DomicilioProveedorPk pk) throws DomicilioProveedorDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + SQL_DELETE + " with PK: " + pk);
			}
		
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setString( 1, pk.getProveedorIdproveedor() );
			stmt.setString( 2, pk.getProveedorTipodeidentificacion() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			if (logger.isDebugEnabled()) {
				logger.debug( rows + " rows affected (" + (t2-t1) + " ms)");
			}
		
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new DomicilioProveedorDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the domicilio_proveedor table that matches the specified primary-key value.
	 */
	public DomicilioProveedor findByPrimaryKey(DomicilioProveedorPk pk) throws DomicilioProveedorDaoException
	{
		return findByPrimaryKey( pk.getProveedorIdproveedor(), pk.getProveedorTipodeidentificacion() );
	}

	/** 
	 * Returns all rows from the domicilio_proveedor table that match the criteria 'Proveedor_idProveedor = :proveedorIdproveedor AND Proveedor_tipoDeIdentificacion = :proveedorTipodeidentificacion'.
	 */
	public DomicilioProveedor findByPrimaryKey(String proveedorIdproveedor, String proveedorTipodeidentificacion) throws DomicilioProveedorDaoException
	{
		DomicilioProveedor ret[] = findByDynamicSelect( SQL_SELECT + " WHERE Proveedor_idProveedor = ? AND Proveedor_tipoDeIdentificacion = ?", new Object[] { proveedorIdproveedor, proveedorTipodeidentificacion } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the domicilio_proveedor table that match the criteria ''.
	 */
	public DomicilioProveedor[] findAll() throws DomicilioProveedorDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY Proveedor_idProveedor, Proveedor_tipoDeIdentificacion", null );
	}

	/** 
	 * Returns all rows from the domicilio_proveedor table that match the criteria 'Municipio_idMunicipio = :municipioIdmunicipio'.
	 */
	public DomicilioProveedor[] findByMunicipio(String municipioIdmunicipio) throws DomicilioProveedorDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Municipio_idMunicipio = ?", new Object[] { municipioIdmunicipio } );
	}

	/** 
	 * Returns all rows from the domicilio_proveedor table that match the criteria 'Proveedor_idProveedor = :proveedorIdproveedor AND Proveedor_tipoDeIdentificacion = :proveedorTipodeidentificacion'.
	 */
	public DomicilioProveedor[] findByProveedor(String proveedorIdproveedor, String proveedorTipodeidentificacion) throws DomicilioProveedorDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Proveedor_idProveedor = ? AND Proveedor_tipoDeIdentificacion = ?", new Object[] { proveedorIdproveedor, proveedorTipodeidentificacion } );
	}

	/** 
	 * Returns all rows from the domicilio_proveedor table that match the criteria 'Proveedor_idProveedor = :proveedorIdproveedor'.
	 */
	public DomicilioProveedor[] findWhereProveedorIdproveedorEquals(String proveedorIdproveedor) throws DomicilioProveedorDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Proveedor_idProveedor = ? ORDER BY Proveedor_idProveedor", new Object[] { proveedorIdproveedor } );
	}

	/** 
	 * Returns all rows from the domicilio_proveedor table that match the criteria 'Proveedor_tipoDeIdentificacion = :proveedorTipodeidentificacion'.
	 */
	public DomicilioProveedor[] findWhereProveedorTipodeidentificacionEquals(String proveedorTipodeidentificacion) throws DomicilioProveedorDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Proveedor_tipoDeIdentificacion = ? ORDER BY Proveedor_tipoDeIdentificacion", new Object[] { proveedorTipodeidentificacion } );
	}

	/** 
	 * Returns all rows from the domicilio_proveedor table that match the criteria 'telefono = :telefono'.
	 */
	public DomicilioProveedor[] findWhereTelefonoEquals(String telefono) throws DomicilioProveedorDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE telefono = ? ORDER BY telefono", new Object[] { telefono } );
	}

	/** 
	 * Returns all rows from the domicilio_proveedor table that match the criteria 'direccion = :direccion'.
	 */
	public DomicilioProveedor[] findWhereDireccionEquals(String direccion) throws DomicilioProveedorDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE direccion = ? ORDER BY direccion", new Object[] { direccion } );
	}

	/** 
	 * Returns all rows from the domicilio_proveedor table that match the criteria 'barrio = :barrio'.
	 */
	public DomicilioProveedor[] findWhereBarrioEquals(String barrio) throws DomicilioProveedorDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE barrio = ? ORDER BY barrio", new Object[] { barrio } );
	}

	/** 
	 * Returns all rows from the domicilio_proveedor table that match the criteria 'localidad = :localidad'.
	 */
	public DomicilioProveedor[] findWhereLocalidadEquals(String localidad) throws DomicilioProveedorDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE localidad = ? ORDER BY localidad", new Object[] { localidad } );
	}

	/** 
	 * Returns all rows from the domicilio_proveedor table that match the criteria 'Municipio_idMunicipio = :municipioIdmunicipio'.
	 */
	public DomicilioProveedor[] findWhereMunicipioIdmunicipioEquals(String municipioIdmunicipio) throws DomicilioProveedorDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Municipio_idMunicipio = ? ORDER BY Municipio_idMunicipio", new Object[] { municipioIdmunicipio } );
	}

	/**
	 * Method 'DomicilioProveedorDaoImpl'
	 * 
	 */
	public DomicilioProveedorDaoImpl()
	{
	}

	/**
	 * Method 'DomicilioProveedorDaoImpl'
	 * 
	 * @param userConn
	 */
	public DomicilioProveedorDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "tiendaenlinea.domicilio_proveedor";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected DomicilioProveedor fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			DomicilioProveedor dto = new DomicilioProveedor();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected DomicilioProveedor[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			DomicilioProveedor dto = new DomicilioProveedor();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		DomicilioProveedor ret[] = new DomicilioProveedor[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(DomicilioProveedor dto, ResultSet rs) throws SQLException
	{
		dto.setProveedorIdproveedor( rs.getString( COLUMN_PROVEEDOR_IDPROVEEDOR ) );
		dto.setProveedorTipodeidentificacion( rs.getString( COLUMN_PROVEEDOR_TIPODEIDENTIFICACION ) );
		dto.setTelefono( rs.getString( COLUMN_TELEFONO ) );
		dto.setDireccion( rs.getString( COLUMN_DIRECCION ) );
		dto.setBarrio( rs.getString( COLUMN_BARRIO ) );
		dto.setLocalidad( rs.getString( COLUMN_LOCALIDAD ) );
		dto.setMunicipioIdmunicipio( rs.getString( COLUMN_MUNICIPIO_IDMUNICIPIO ) );
		reset(dto);
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(DomicilioProveedor dto)
	{
		dto.setProveedorIdproveedorModified( false );
		dto.setProveedorTipodeidentificacionModified( false );
		dto.setTelefonoModified( false );
		dto.setDireccionModified( false );
		dto.setBarrioModified( false );
		dto.setLocalidadModified( false );
		dto.setMunicipioIdmunicipioModified( false );
	}

	/** 
	 * Returns all rows from the domicilio_proveedor table that match the specified arbitrary SQL statement
	 */
	public DomicilioProveedor[] findByDynamicSelect(String sql, Object[] sqlParams) throws DomicilioProveedorDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + SQL);
			}
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new DomicilioProveedorDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the domicilio_proveedor table that match the specified arbitrary SQL statement
	 */
	public DomicilioProveedor[] findByDynamicWhere(String sql, Object[] sqlParams) throws DomicilioProveedorDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + SQL);
			}
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new DomicilioProveedorDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
