/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.tiendaenlinea.integracion.dao;

import edu.co.sena.tiendaenlinea.integracion.dto.*;
import edu.co.sena.tiendaenlinea.integracion.exceptions.*;

public interface ProveedorDao
{
	/** 
	 * Inserts a new row in the proveedor table.
	 */
	public ProveedorPk insert(Proveedor dto) throws ProveedorDaoException;

	/** 
	 * Updates a single row in the proveedor table.
	 */
	public void update(ProveedorPk pk, Proveedor dto) throws ProveedorDaoException;

	/** 
	 * Deletes a single row in the proveedor table.
	 */
	public void delete(ProveedorPk pk) throws ProveedorDaoException;

	/** 
	 * Returns the rows from the proveedor table that matches the specified primary-key value.
	 */
	public Proveedor findByPrimaryKey(ProveedorPk pk) throws ProveedorDaoException;

	/** 
	 * Returns all rows from the proveedor table that match the criteria 'idProveedor = :idProveedor AND tipoDeIdentificacion = :tipoDeIdentificacion'.
	 */
	public Proveedor findByPrimaryKey(String idProveedor, String tipoDeIdentificacion) throws ProveedorDaoException;

	/** 
	 * Returns all rows from the proveedor table that match the criteria ''.
	 */
	public Proveedor[] findAll() throws ProveedorDaoException;

	/** 
	 * Returns all rows from the proveedor table that match the criteria 'idProveedor = :idProveedor'.
	 */
	public Proveedor[] findWhereIdProveedorEquals(String idProveedor) throws ProveedorDaoException;

	/** 
	 * Returns all rows from the proveedor table that match the criteria 'tipoDeIdentificacion = :tipoDeIdentificacion'.
	 */
	public Proveedor[] findWhereTipoDeIdentificacionEquals(String tipoDeIdentificacion) throws ProveedorDaoException;

	/** 
	 * Returns all rows from the proveedor table that match the criteria 'nombre = :nombre'.
	 */
	public Proveedor[] findWhereNombreEquals(String nombre) throws ProveedorDaoException;

	/** 
	 * Returns all rows from the proveedor table that match the criteria 'telefono = :telefono'.
	 */
	public Proveedor[] findWhereTelefonoEquals(String telefono) throws ProveedorDaoException;

	/** 
	 * Returns all rows from the proveedor table that match the criteria 'email = :email'.
	 */
	public Proveedor[] findWhereEmailEquals(String email) throws ProveedorDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the proveedor table that match the specified arbitrary SQL statement
	 */
	public Proveedor[] findByDynamicSelect(String sql, Object[] sqlParams) throws ProveedorDaoException;

	/** 
	 * Returns all rows from the proveedor table that match the specified arbitrary SQL statement
	 */
	public Proveedor[] findByDynamicWhere(String sql, Object[] sqlParams) throws ProveedorDaoException;

}
