/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.tiendaenlinea.negocio.examples;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import edu.co.sena.tiendaenlinea.integracion.dao.FacturaDao;
import edu.co.sena.tiendaenlinea.integracion.dto.Factura;
import edu.co.sena.tiendaenlinea.integracion.exceptions.FacturaDaoException;
import edu.co.sena.tiendaenlinea.integracion.factory.FacturaDaoFactory;

public class FacturaDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findByCuenta("", "");
		// findWhereIdFacturaEquals(0);
		// findWhereFechaEquals(null);
		// findWhereTotalEquals(0);
		// findWhereCuentaTipodocumentoEquals("");
		// findWhereCuentaNumerodocumentoEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			FacturaDao _dao = getFacturaDao();
			Factura _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByCuenta'
	 * 
	 * @param cuentaTipodocumento
	 * @param cuentaNumerodocumento
	 */
	public static void findByCuenta(String cuentaTipodocumento, String cuentaNumerodocumento)
	{
		try {
			FacturaDao _dao = getFacturaDao();
			Factura _result[] = _dao.findByCuenta(cuentaTipodocumento, cuentaNumerodocumento);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdFacturaEquals'
	 * 
	 * @param idFactura
	 */
	public static void findWhereIdFacturaEquals(int idFactura)
	{
		try {
			FacturaDao _dao = getFacturaDao();
			Factura _result[] = _dao.findWhereIdFacturaEquals(idFactura);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereFechaEquals'
	 * 
	 * @param fecha
	 */
	public static void findWhereFechaEquals(Date fecha)
	{
		try {
			FacturaDao _dao = getFacturaDao();
			Factura _result[] = _dao.findWhereFechaEquals(fecha);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereTotalEquals'
	 * 
	 * @param total
	 */
	public static void findWhereTotalEquals(float total)
	{
		try {
			FacturaDao _dao = getFacturaDao();
			Factura _result[] = _dao.findWhereTotalEquals(total);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCuentaTipodocumentoEquals'
	 * 
	 * @param cuentaTipodocumento
	 */
	public static void findWhereCuentaTipodocumentoEquals(String cuentaTipodocumento)
	{
		try {
			FacturaDao _dao = getFacturaDao();
			Factura _result[] = _dao.findWhereCuentaTipodocumentoEquals(cuentaTipodocumento);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCuentaNumerodocumentoEquals'
	 * 
	 * @param cuentaNumerodocumento
	 */
	public static void findWhereCuentaNumerodocumentoEquals(String cuentaNumerodocumento)
	{
		try {
			FacturaDao _dao = getFacturaDao();
			Factura _result[] = _dao.findWhereCuentaNumerodocumentoEquals(cuentaNumerodocumento);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getFacturaDao'
	 * 
	 * @return FacturaDao
	 */
	public static FacturaDao getFacturaDao()
	{
		return FacturaDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Factura dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getIdFactura() );
		buf.append( ", " );
		buf.append( dto.getFecha() );
		buf.append( ", " );
		buf.append( dto.getTotal() );
		buf.append( ", " );
		buf.append( dto.getCuentaTipodocumento() );
		buf.append( ", " );
		buf.append( dto.getCuentaNumerodocumento() );
		System.out.println( buf.toString() );
	}

}
