/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.tiendaenlinea.negocio.examples;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import edu.co.sena.tiendaenlinea.integracion.dao.ProveedorDao;
import edu.co.sena.tiendaenlinea.integracion.dto.Proveedor;
import edu.co.sena.tiendaenlinea.integracion.exceptions.ProveedorDaoException;
import edu.co.sena.tiendaenlinea.integracion.factory.ProveedorDaoFactory;

public class ProveedorDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereIdProveedorEquals("");
		// findWhereTipoDeIdentificacionEquals("");
		// findWhereNombreEquals("");
		// findWhereTelefonoEquals("");
		// findWhereEmailEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			ProveedorDao _dao = getProveedorDao();
			Proveedor _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdProveedorEquals'
	 * 
	 * @param idProveedor
	 */
	public static void findWhereIdProveedorEquals(String idProveedor)
	{
		try {
			ProveedorDao _dao = getProveedorDao();
			Proveedor _result[] = _dao.findWhereIdProveedorEquals(idProveedor);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereTipoDeIdentificacionEquals'
	 * 
	 * @param tipoDeIdentificacion
	 */
	public static void findWhereTipoDeIdentificacionEquals(String tipoDeIdentificacion)
	{
		try {
			ProveedorDao _dao = getProveedorDao();
			Proveedor _result[] = _dao.findWhereTipoDeIdentificacionEquals(tipoDeIdentificacion);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNombreEquals'
	 * 
	 * @param nombre
	 */
	public static void findWhereNombreEquals(String nombre)
	{
		try {
			ProveedorDao _dao = getProveedorDao();
			Proveedor _result[] = _dao.findWhereNombreEquals(nombre);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereTelefonoEquals'
	 * 
	 * @param telefono
	 */
	public static void findWhereTelefonoEquals(String telefono)
	{
		try {
			ProveedorDao _dao = getProveedorDao();
			Proveedor _result[] = _dao.findWhereTelefonoEquals(telefono);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereEmailEquals'
	 * 
	 * @param email
	 */
	public static void findWhereEmailEquals(String email)
	{
		try {
			ProveedorDao _dao = getProveedorDao();
			Proveedor _result[] = _dao.findWhereEmailEquals(email);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getProveedorDao'
	 * 
	 * @return ProveedorDao
	 */
	public static ProveedorDao getProveedorDao()
	{
		return ProveedorDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Proveedor dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getIdProveedor() );
		buf.append( ", " );
		buf.append( dto.getTipoDeIdentificacion() );
		buf.append( ", " );
		buf.append( dto.getNombre() );
		buf.append( ", " );
		buf.append( dto.getTelefono() );
		buf.append( ", " );
		buf.append( dto.getEmail() );
		System.out.println( buf.toString() );
	}

}
