/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.tiendaenlinea.integracion.dto;

import edu.co.sena.tiendaenlinea.integracion.dao.*;
import edu.co.sena.tiendaenlinea.integracion.factory.*;
import edu.co.sena.tiendaenlinea.integracion.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Carritodecompras implements Serializable
{
	/** 
	 * This attribute maps to the column idCarritoDeCompras in the carritodecompras table.
	 */
	protected String idCarritoDeCompras;

	/** 
	 * This attribute represents whether the attribute idCarritoDeCompras has been modified since being read from the database.
	 */
	protected boolean idCarritoDeComprasModified = false;

	/** 
	 * This attribute maps to the column subtotal in the carritodecompras table.
	 */
	protected float subtotal;

	/** 
	 * This attribute represents whether the attribute subtotal has been modified since being read from the database.
	 */
	protected boolean subtotalModified = false;

	/** 
	 * This attribute maps to the column precioTotal in the carritodecompras table.
	 */
	protected float precioTotal;

	/** 
	 * This attribute represents whether the attribute precioTotal has been modified since being read from the database.
	 */
	protected boolean precioTotalModified = false;

	/** 
	 * This attribute maps to the column impuestos in the carritodecompras table.
	 */
	protected float impuestos;

	/** 
	 * This attribute represents whether the attribute impuestos has been modified since being read from the database.
	 */
	protected boolean impuestosModified = false;

	/**
	 * Method 'Carritodecompras'
	 * 
	 */
	public Carritodecompras()
	{
	}

	/**
	 * Method 'getIdCarritoDeCompras'
	 * 
	 * @return String
	 */
	public String getIdCarritoDeCompras()
	{
		return idCarritoDeCompras;
	}

	/**
	 * Method 'setIdCarritoDeCompras'
	 * 
	 * @param idCarritoDeCompras
	 */
	public void setIdCarritoDeCompras(String idCarritoDeCompras)
	{
		this.idCarritoDeCompras = idCarritoDeCompras;
		this.idCarritoDeComprasModified = true;
	}

	/** 
	 * Sets the value of idCarritoDeComprasModified
	 */
	public void setIdCarritoDeComprasModified(boolean idCarritoDeComprasModified)
	{
		this.idCarritoDeComprasModified = idCarritoDeComprasModified;
	}

	/** 
	 * Gets the value of idCarritoDeComprasModified
	 */
	public boolean isIdCarritoDeComprasModified()
	{
		return idCarritoDeComprasModified;
	}

	/**
	 * Method 'getSubtotal'
	 * 
	 * @return float
	 */
	public float getSubtotal()
	{
		return subtotal;
	}

	/**
	 * Method 'setSubtotal'
	 * 
	 * @param subtotal
	 */
	public void setSubtotal(float subtotal)
	{
		this.subtotal = subtotal;
		this.subtotalModified = true;
	}

	/** 
	 * Sets the value of subtotalModified
	 */
	public void setSubtotalModified(boolean subtotalModified)
	{
		this.subtotalModified = subtotalModified;
	}

	/** 
	 * Gets the value of subtotalModified
	 */
	public boolean isSubtotalModified()
	{
		return subtotalModified;
	}

	/**
	 * Method 'getPrecioTotal'
	 * 
	 * @return float
	 */
	public float getPrecioTotal()
	{
		return precioTotal;
	}

	/**
	 * Method 'setPrecioTotal'
	 * 
	 * @param precioTotal
	 */
	public void setPrecioTotal(float precioTotal)
	{
		this.precioTotal = precioTotal;
		this.precioTotalModified = true;
	}

	/** 
	 * Sets the value of precioTotalModified
	 */
	public void setPrecioTotalModified(boolean precioTotalModified)
	{
		this.precioTotalModified = precioTotalModified;
	}

	/** 
	 * Gets the value of precioTotalModified
	 */
	public boolean isPrecioTotalModified()
	{
		return precioTotalModified;
	}

	/**
	 * Method 'getImpuestos'
	 * 
	 * @return float
	 */
	public float getImpuestos()
	{
		return impuestos;
	}

	/**
	 * Method 'setImpuestos'
	 * 
	 * @param impuestos
	 */
	public void setImpuestos(float impuestos)
	{
		this.impuestos = impuestos;
		this.impuestosModified = true;
	}

	/** 
	 * Sets the value of impuestosModified
	 */
	public void setImpuestosModified(boolean impuestosModified)
	{
		this.impuestosModified = impuestosModified;
	}

	/** 
	 * Gets the value of impuestosModified
	 */
	public boolean isImpuestosModified()
	{
		return impuestosModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Carritodecompras)) {
			return false;
		}
		
		final Carritodecompras _cast = (Carritodecompras) _other;
		if (idCarritoDeCompras == null ? _cast.idCarritoDeCompras != idCarritoDeCompras : !idCarritoDeCompras.equals( _cast.idCarritoDeCompras )) {
			return false;
		}
		
		if (idCarritoDeComprasModified != _cast.idCarritoDeComprasModified) {
			return false;
		}
		
		if (subtotal != _cast.subtotal) {
			return false;
		}
		
		if (subtotalModified != _cast.subtotalModified) {
			return false;
		}
		
		if (precioTotal != _cast.precioTotal) {
			return false;
		}
		
		if (precioTotalModified != _cast.precioTotalModified) {
			return false;
		}
		
		if (impuestos != _cast.impuestos) {
			return false;
		}
		
		if (impuestosModified != _cast.impuestosModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idCarritoDeCompras != null) {
			_hashCode = 29 * _hashCode + idCarritoDeCompras.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (idCarritoDeComprasModified ? 1 : 0);
		_hashCode = 29 * _hashCode + Float.floatToIntBits(subtotal);
		_hashCode = 29 * _hashCode + (subtotalModified ? 1 : 0);
		_hashCode = 29 * _hashCode + Float.floatToIntBits(precioTotal);
		_hashCode = 29 * _hashCode + (precioTotalModified ? 1 : 0);
		_hashCode = 29 * _hashCode + Float.floatToIntBits(impuestos);
		_hashCode = 29 * _hashCode + (impuestosModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return CarritodecomprasPk
	 */
	public CarritodecomprasPk createPk()
	{
		return new CarritodecomprasPk(idCarritoDeCompras);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.tiendaenlinea.integracion.dto.Carritodecompras: " );
		ret.append( "idCarritoDeCompras=" + idCarritoDeCompras );
		ret.append( ", subtotal=" + subtotal );
		ret.append( ", precioTotal=" + precioTotal );
		ret.append( ", impuestos=" + impuestos );
		return ret.toString();
	}

}
