/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.tiendaenlinea.integracion.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the carritodecompras table.
 */
public class CarritodecomprasPk implements Serializable
{
	protected String idCarritoDeCompras;

	/** 
	 * Sets the value of idCarritoDeCompras
	 */
	public void setIdCarritoDeCompras(String idCarritoDeCompras)
	{
		this.idCarritoDeCompras = idCarritoDeCompras;
	}

	/** 
	 * Gets the value of idCarritoDeCompras
	 */
	public String getIdCarritoDeCompras()
	{
		return idCarritoDeCompras;
	}

	/**
	 * Method 'CarritodecomprasPk'
	 * 
	 */
	public CarritodecomprasPk()
	{
	}

	/**
	 * Method 'CarritodecomprasPk'
	 * 
	 * @param idCarritoDeCompras
	 */
	public CarritodecomprasPk(final String idCarritoDeCompras)
	{
		this.idCarritoDeCompras = idCarritoDeCompras;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof CarritodecomprasPk)) {
			return false;
		}
		
		final CarritodecomprasPk _cast = (CarritodecomprasPk) _other;
		if (idCarritoDeCompras == null ? _cast.idCarritoDeCompras != idCarritoDeCompras : !idCarritoDeCompras.equals( _cast.idCarritoDeCompras )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idCarritoDeCompras != null) {
			_hashCode = 29 * _hashCode + idCarritoDeCompras.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.tiendaenlinea.integracion.dto.CarritodecomprasPk: " );
		ret.append( "idCarritoDeCompras=" + idCarritoDeCompras );
		return ret.toString();
	}

}
