/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.tiendaenlinea.integracion.dto;

import edu.co.sena.tiendaenlinea.integracion.dao.*;
import edu.co.sena.tiendaenlinea.integracion.factory.*;
import edu.co.sena.tiendaenlinea.integracion.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Cuenta implements Serializable
{
	/** 
	 * This attribute maps to the column tipoDocumento in the cuenta table.
	 */
	protected String tipoDocumento;

	/** 
	 * This attribute represents whether the attribute tipoDocumento has been modified since being read from the database.
	 */
	protected boolean tipoDocumentoModified = false;

	/** 
	 * This attribute maps to the column numeroDocumento in the cuenta table.
	 */
	protected String numeroDocumento;

	/** 
	 * This attribute represents whether the attribute numeroDocumento has been modified since being read from the database.
	 */
	protected boolean numeroDocumentoModified = false;

	/** 
	 * This attribute maps to the column primerNombre in the cuenta table.
	 */
	protected String primerNombre;

	/** 
	 * This attribute represents whether the attribute primerNombre has been modified since being read from the database.
	 */
	protected boolean primerNombreModified = false;

	/** 
	 * This attribute maps to the column segundoNombre in the cuenta table.
	 */
	protected String segundoNombre;

	/** 
	 * This attribute represents whether the attribute segundoNombre has been modified since being read from the database.
	 */
	protected boolean segundoNombreModified = false;

	/** 
	 * This attribute maps to the column primerApellido in the cuenta table.
	 */
	protected String primerApellido;

	/** 
	 * This attribute represents whether the attribute primerApellido has been modified since being read from the database.
	 */
	protected boolean primerApellidoModified = false;

	/** 
	 * This attribute maps to the column segundoApellido in the cuenta table.
	 */
	protected String segundoApellido;

	/** 
	 * This attribute represents whether the attribute segundoApellido has been modified since being read from the database.
	 */
	protected boolean segundoApellidoModified = false;

	/** 
	 * This attribute maps to the column contrasena in the cuenta table.
	 */
	protected String contrasena;

	/** 
	 * This attribute represents whether the attribute contrasena has been modified since being read from the database.
	 */
	protected boolean contrasenaModified = false;

	/** 
	 * This attribute maps to the column email in the cuenta table.
	 */
	protected String email;

	/** 
	 * This attribute represents whether the attribute email has been modified since being read from the database.
	 */
	protected boolean emailModified = false;

	/** 
	 * This attribute maps to the column Usuario_idUsuario in the cuenta table.
	 */
	protected String usuarioIdusuario;

	/** 
	 * This attribute represents whether the attribute usuarioIdusuario has been modified since being read from the database.
	 */
	protected boolean usuarioIdusuarioModified = false;

	/**
	 * Method 'Cuenta'
	 * 
	 */
	public Cuenta()
	{
	}

	/**
	 * Method 'getTipoDocumento'
	 * 
	 * @return String
	 */
	public String getTipoDocumento()
	{
		return tipoDocumento;
	}

	/**
	 * Method 'setTipoDocumento'
	 * 
	 * @param tipoDocumento
	 */
	public void setTipoDocumento(String tipoDocumento)
	{
		this.tipoDocumento = tipoDocumento;
		this.tipoDocumentoModified = true;
	}

	/** 
	 * Sets the value of tipoDocumentoModified
	 */
	public void setTipoDocumentoModified(boolean tipoDocumentoModified)
	{
		this.tipoDocumentoModified = tipoDocumentoModified;
	}

	/** 
	 * Gets the value of tipoDocumentoModified
	 */
	public boolean isTipoDocumentoModified()
	{
		return tipoDocumentoModified;
	}

	/**
	 * Method 'getNumeroDocumento'
	 * 
	 * @return String
	 */
	public String getNumeroDocumento()
	{
		return numeroDocumento;
	}

	/**
	 * Method 'setNumeroDocumento'
	 * 
	 * @param numeroDocumento
	 */
	public void setNumeroDocumento(String numeroDocumento)
	{
		this.numeroDocumento = numeroDocumento;
		this.numeroDocumentoModified = true;
	}

	/** 
	 * Sets the value of numeroDocumentoModified
	 */
	public void setNumeroDocumentoModified(boolean numeroDocumentoModified)
	{
		this.numeroDocumentoModified = numeroDocumentoModified;
	}

	/** 
	 * Gets the value of numeroDocumentoModified
	 */
	public boolean isNumeroDocumentoModified()
	{
		return numeroDocumentoModified;
	}

	/**
	 * Method 'getPrimerNombre'
	 * 
	 * @return String
	 */
	public String getPrimerNombre()
	{
		return primerNombre;
	}

	/**
	 * Method 'setPrimerNombre'
	 * 
	 * @param primerNombre
	 */
	public void setPrimerNombre(String primerNombre)
	{
		this.primerNombre = primerNombre;
		this.primerNombreModified = true;
	}

	/** 
	 * Sets the value of primerNombreModified
	 */
	public void setPrimerNombreModified(boolean primerNombreModified)
	{
		this.primerNombreModified = primerNombreModified;
	}

	/** 
	 * Gets the value of primerNombreModified
	 */
	public boolean isPrimerNombreModified()
	{
		return primerNombreModified;
	}

	/**
	 * Method 'getSegundoNombre'
	 * 
	 * @return String
	 */
	public String getSegundoNombre()
	{
		return segundoNombre;
	}

	/**
	 * Method 'setSegundoNombre'
	 * 
	 * @param segundoNombre
	 */
	public void setSegundoNombre(String segundoNombre)
	{
		this.segundoNombre = segundoNombre;
		this.segundoNombreModified = true;
	}

	/** 
	 * Sets the value of segundoNombreModified
	 */
	public void setSegundoNombreModified(boolean segundoNombreModified)
	{
		this.segundoNombreModified = segundoNombreModified;
	}

	/** 
	 * Gets the value of segundoNombreModified
	 */
	public boolean isSegundoNombreModified()
	{
		return segundoNombreModified;
	}

	/**
	 * Method 'getPrimerApellido'
	 * 
	 * @return String
	 */
	public String getPrimerApellido()
	{
		return primerApellido;
	}

	/**
	 * Method 'setPrimerApellido'
	 * 
	 * @param primerApellido
	 */
	public void setPrimerApellido(String primerApellido)
	{
		this.primerApellido = primerApellido;
		this.primerApellidoModified = true;
	}

	/** 
	 * Sets the value of primerApellidoModified
	 */
	public void setPrimerApellidoModified(boolean primerApellidoModified)
	{
		this.primerApellidoModified = primerApellidoModified;
	}

	/** 
	 * Gets the value of primerApellidoModified
	 */
	public boolean isPrimerApellidoModified()
	{
		return primerApellidoModified;
	}

	/**
	 * Method 'getSegundoApellido'
	 * 
	 * @return String
	 */
	public String getSegundoApellido()
	{
		return segundoApellido;
	}

	/**
	 * Method 'setSegundoApellido'
	 * 
	 * @param segundoApellido
	 */
	public void setSegundoApellido(String segundoApellido)
	{
		this.segundoApellido = segundoApellido;
		this.segundoApellidoModified = true;
	}

	/** 
	 * Sets the value of segundoApellidoModified
	 */
	public void setSegundoApellidoModified(boolean segundoApellidoModified)
	{
		this.segundoApellidoModified = segundoApellidoModified;
	}

	/** 
	 * Gets the value of segundoApellidoModified
	 */
	public boolean isSegundoApellidoModified()
	{
		return segundoApellidoModified;
	}

	/**
	 * Method 'getContrasena'
	 * 
	 * @return String
	 */
	public String getContrasena()
	{
		return contrasena;
	}

	/**
	 * Method 'setContrasena'
	 * 
	 * @param contrasena
	 */
	public void setContrasena(String contrasena)
	{
		this.contrasena = contrasena;
		this.contrasenaModified = true;
	}

	/** 
	 * Sets the value of contrasenaModified
	 */
	public void setContrasenaModified(boolean contrasenaModified)
	{
		this.contrasenaModified = contrasenaModified;
	}

	/** 
	 * Gets the value of contrasenaModified
	 */
	public boolean isContrasenaModified()
	{
		return contrasenaModified;
	}

	/**
	 * Method 'getEmail'
	 * 
	 * @return String
	 */
	public String getEmail()
	{
		return email;
	}

	/**
	 * Method 'setEmail'
	 * 
	 * @param email
	 */
	public void setEmail(String email)
	{
		this.email = email;
		this.emailModified = true;
	}

	/** 
	 * Sets the value of emailModified
	 */
	public void setEmailModified(boolean emailModified)
	{
		this.emailModified = emailModified;
	}

	/** 
	 * Gets the value of emailModified
	 */
	public boolean isEmailModified()
	{
		return emailModified;
	}

	/**
	 * Method 'getUsuarioIdusuario'
	 * 
	 * @return String
	 */
	public String getUsuarioIdusuario()
	{
		return usuarioIdusuario;
	}

	/**
	 * Method 'setUsuarioIdusuario'
	 * 
	 * @param usuarioIdusuario
	 */
	public void setUsuarioIdusuario(String usuarioIdusuario)
	{
		this.usuarioIdusuario = usuarioIdusuario;
		this.usuarioIdusuarioModified = true;
	}

	/** 
	 * Sets the value of usuarioIdusuarioModified
	 */
	public void setUsuarioIdusuarioModified(boolean usuarioIdusuarioModified)
	{
		this.usuarioIdusuarioModified = usuarioIdusuarioModified;
	}

	/** 
	 * Gets the value of usuarioIdusuarioModified
	 */
	public boolean isUsuarioIdusuarioModified()
	{
		return usuarioIdusuarioModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Cuenta)) {
			return false;
		}
		
		final Cuenta _cast = (Cuenta) _other;
		if (tipoDocumento == null ? _cast.tipoDocumento != tipoDocumento : !tipoDocumento.equals( _cast.tipoDocumento )) {
			return false;
		}
		
		if (tipoDocumentoModified != _cast.tipoDocumentoModified) {
			return false;
		}
		
		if (numeroDocumento == null ? _cast.numeroDocumento != numeroDocumento : !numeroDocumento.equals( _cast.numeroDocumento )) {
			return false;
		}
		
		if (numeroDocumentoModified != _cast.numeroDocumentoModified) {
			return false;
		}
		
		if (primerNombre == null ? _cast.primerNombre != primerNombre : !primerNombre.equals( _cast.primerNombre )) {
			return false;
		}
		
		if (primerNombreModified != _cast.primerNombreModified) {
			return false;
		}
		
		if (segundoNombre == null ? _cast.segundoNombre != segundoNombre : !segundoNombre.equals( _cast.segundoNombre )) {
			return false;
		}
		
		if (segundoNombreModified != _cast.segundoNombreModified) {
			return false;
		}
		
		if (primerApellido == null ? _cast.primerApellido != primerApellido : !primerApellido.equals( _cast.primerApellido )) {
			return false;
		}
		
		if (primerApellidoModified != _cast.primerApellidoModified) {
			return false;
		}
		
		if (segundoApellido == null ? _cast.segundoApellido != segundoApellido : !segundoApellido.equals( _cast.segundoApellido )) {
			return false;
		}
		
		if (segundoApellidoModified != _cast.segundoApellidoModified) {
			return false;
		}
		
		if (contrasena == null ? _cast.contrasena != contrasena : !contrasena.equals( _cast.contrasena )) {
			return false;
		}
		
		if (contrasenaModified != _cast.contrasenaModified) {
			return false;
		}
		
		if (email == null ? _cast.email != email : !email.equals( _cast.email )) {
			return false;
		}
		
		if (emailModified != _cast.emailModified) {
			return false;
		}
		
		if (usuarioIdusuario == null ? _cast.usuarioIdusuario != usuarioIdusuario : !usuarioIdusuario.equals( _cast.usuarioIdusuario )) {
			return false;
		}
		
		if (usuarioIdusuarioModified != _cast.usuarioIdusuarioModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (tipoDocumento != null) {
			_hashCode = 29 * _hashCode + tipoDocumento.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (tipoDocumentoModified ? 1 : 0);
		if (numeroDocumento != null) {
			_hashCode = 29 * _hashCode + numeroDocumento.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (numeroDocumentoModified ? 1 : 0);
		if (primerNombre != null) {
			_hashCode = 29 * _hashCode + primerNombre.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (primerNombreModified ? 1 : 0);
		if (segundoNombre != null) {
			_hashCode = 29 * _hashCode + segundoNombre.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (segundoNombreModified ? 1 : 0);
		if (primerApellido != null) {
			_hashCode = 29 * _hashCode + primerApellido.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (primerApellidoModified ? 1 : 0);
		if (segundoApellido != null) {
			_hashCode = 29 * _hashCode + segundoApellido.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (segundoApellidoModified ? 1 : 0);
		if (contrasena != null) {
			_hashCode = 29 * _hashCode + contrasena.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (contrasenaModified ? 1 : 0);
		if (email != null) {
			_hashCode = 29 * _hashCode + email.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (emailModified ? 1 : 0);
		if (usuarioIdusuario != null) {
			_hashCode = 29 * _hashCode + usuarioIdusuario.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (usuarioIdusuarioModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return CuentaPk
	 */
	public CuentaPk createPk()
	{
		return new CuentaPk(tipoDocumento, numeroDocumento);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.tiendaenlinea.integracion.dto.Cuenta: " );
		ret.append( "tipoDocumento=" + tipoDocumento );
		ret.append( ", numeroDocumento=" + numeroDocumento );
		ret.append( ", primerNombre=" + primerNombre );
		ret.append( ", segundoNombre=" + segundoNombre );
		ret.append( ", primerApellido=" + primerApellido );
		ret.append( ", segundoApellido=" + segundoApellido );
		ret.append( ", contrasena=" + contrasena );
		ret.append( ", email=" + email );
		ret.append( ", usuarioIdusuario=" + usuarioIdusuario );
		return ret.toString();
	}

}
