/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.tiendaenlinea.integracion.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the domicilio_cuenta table.
 */
public class DomicilioCuentaPk implements Serializable
{
	protected String cuentaTipodocumento;

	protected String cuentaNumerodocumento;

	/** 
	 * Sets the value of cuentaTipodocumento
	 */
	public void setCuentaTipodocumento(String cuentaTipodocumento)
	{
		this.cuentaTipodocumento = cuentaTipodocumento;
	}

	/** 
	 * Gets the value of cuentaTipodocumento
	 */
	public String getCuentaTipodocumento()
	{
		return cuentaTipodocumento;
	}

	/** 
	 * Sets the value of cuentaNumerodocumento
	 */
	public void setCuentaNumerodocumento(String cuentaNumerodocumento)
	{
		this.cuentaNumerodocumento = cuentaNumerodocumento;
	}

	/** 
	 * Gets the value of cuentaNumerodocumento
	 */
	public String getCuentaNumerodocumento()
	{
		return cuentaNumerodocumento;
	}

	/**
	 * Method 'DomicilioCuentaPk'
	 * 
	 */
	public DomicilioCuentaPk()
	{
	}

	/**
	 * Method 'DomicilioCuentaPk'
	 * 
	 * @param cuentaTipodocumento
	 * @param cuentaNumerodocumento
	 */
	public DomicilioCuentaPk(final String cuentaTipodocumento, final String cuentaNumerodocumento)
	{
		this.cuentaTipodocumento = cuentaTipodocumento;
		this.cuentaNumerodocumento = cuentaNumerodocumento;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof DomicilioCuentaPk)) {
			return false;
		}
		
		final DomicilioCuentaPk _cast = (DomicilioCuentaPk) _other;
		if (cuentaTipodocumento == null ? _cast.cuentaTipodocumento != cuentaTipodocumento : !cuentaTipodocumento.equals( _cast.cuentaTipodocumento )) {
			return false;
		}
		
		if (cuentaNumerodocumento == null ? _cast.cuentaNumerodocumento != cuentaNumerodocumento : !cuentaNumerodocumento.equals( _cast.cuentaNumerodocumento )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (cuentaTipodocumento != null) {
			_hashCode = 29 * _hashCode + cuentaTipodocumento.hashCode();
		}
		
		if (cuentaNumerodocumento != null) {
			_hashCode = 29 * _hashCode + cuentaNumerodocumento.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.tiendaenlinea.integracion.dto.DomicilioCuentaPk: " );
		ret.append( "cuentaTipodocumento=" + cuentaTipodocumento );
		ret.append( ", cuentaNumerodocumento=" + cuentaNumerodocumento );
		return ret.toString();
	}

}
