/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.tiendaenlinea.integracion.dto;

import edu.co.sena.tiendaenlinea.integracion.dao.*;
import edu.co.sena.tiendaenlinea.integracion.factory.*;
import edu.co.sena.tiendaenlinea.integracion.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Factura implements Serializable
{
	/** 
	 * This attribute maps to the column idFactura in the factura table.
	 */
	protected int idFactura;

	/** 
	 * This attribute represents whether the attribute idFactura has been modified since being read from the database.
	 */
	protected boolean idFacturaModified = false;

	/** 
	 * This attribute maps to the column fecha in the factura table.
	 */
	protected Date fecha;

	/** 
	 * This attribute represents whether the attribute fecha has been modified since being read from the database.
	 */
	protected boolean fechaModified = false;

	/** 
	 * This attribute maps to the column total in the factura table.
	 */
	protected float total;

	/** 
	 * This attribute represents whether the attribute total has been modified since being read from the database.
	 */
	protected boolean totalModified = false;

	/** 
	 * This attribute maps to the column Cuenta_tipoDocumento in the factura table.
	 */
	protected String cuentaTipodocumento;

	/** 
	 * This attribute represents whether the attribute cuentaTipodocumento has been modified since being read from the database.
	 */
	protected boolean cuentaTipodocumentoModified = false;

	/** 
	 * This attribute maps to the column Cuenta_numeroDocumento in the factura table.
	 */
	protected String cuentaNumerodocumento;

	/** 
	 * This attribute represents whether the attribute cuentaNumerodocumento has been modified since being read from the database.
	 */
	protected boolean cuentaNumerodocumentoModified = false;

	/**
	 * Method 'Factura'
	 * 
	 */
	public Factura()
	{
	}

	/**
	 * Method 'getIdFactura'
	 * 
	 * @return int
	 */
	public int getIdFactura()
	{
		return idFactura;
	}

	/**
	 * Method 'setIdFactura'
	 * 
	 * @param idFactura
	 */
	public void setIdFactura(int idFactura)
	{
		this.idFactura = idFactura;
		this.idFacturaModified = true;
	}

	/** 
	 * Sets the value of idFacturaModified
	 */
	public void setIdFacturaModified(boolean idFacturaModified)
	{
		this.idFacturaModified = idFacturaModified;
	}

	/** 
	 * Gets the value of idFacturaModified
	 */
	public boolean isIdFacturaModified()
	{
		return idFacturaModified;
	}

	/**
	 * Method 'getFecha'
	 * 
	 * @return Date
	 */
	public Date getFecha()
	{
		return fecha;
	}

	/**
	 * Method 'setFecha'
	 * 
	 * @param fecha
	 */
	public void setFecha(Date fecha)
	{
		this.fecha = fecha;
		this.fechaModified = true;
	}

	/** 
	 * Sets the value of fechaModified
	 */
	public void setFechaModified(boolean fechaModified)
	{
		this.fechaModified = fechaModified;
	}

	/** 
	 * Gets the value of fechaModified
	 */
	public boolean isFechaModified()
	{
		return fechaModified;
	}

	/**
	 * Method 'getTotal'
	 * 
	 * @return float
	 */
	public float getTotal()
	{
		return total;
	}

	/**
	 * Method 'setTotal'
	 * 
	 * @param total
	 */
	public void setTotal(float total)
	{
		this.total = total;
		this.totalModified = true;
	}

	/** 
	 * Sets the value of totalModified
	 */
	public void setTotalModified(boolean totalModified)
	{
		this.totalModified = totalModified;
	}

	/** 
	 * Gets the value of totalModified
	 */
	public boolean isTotalModified()
	{
		return totalModified;
	}

	/**
	 * Method 'getCuentaTipodocumento'
	 * 
	 * @return String
	 */
	public String getCuentaTipodocumento()
	{
		return cuentaTipodocumento;
	}

	/**
	 * Method 'setCuentaTipodocumento'
	 * 
	 * @param cuentaTipodocumento
	 */
	public void setCuentaTipodocumento(String cuentaTipodocumento)
	{
		this.cuentaTipodocumento = cuentaTipodocumento;
		this.cuentaTipodocumentoModified = true;
	}

	/** 
	 * Sets the value of cuentaTipodocumentoModified
	 */
	public void setCuentaTipodocumentoModified(boolean cuentaTipodocumentoModified)
	{
		this.cuentaTipodocumentoModified = cuentaTipodocumentoModified;
	}

	/** 
	 * Gets the value of cuentaTipodocumentoModified
	 */
	public boolean isCuentaTipodocumentoModified()
	{
		return cuentaTipodocumentoModified;
	}

	/**
	 * Method 'getCuentaNumerodocumento'
	 * 
	 * @return String
	 */
	public String getCuentaNumerodocumento()
	{
		return cuentaNumerodocumento;
	}

	/**
	 * Method 'setCuentaNumerodocumento'
	 * 
	 * @param cuentaNumerodocumento
	 */
	public void setCuentaNumerodocumento(String cuentaNumerodocumento)
	{
		this.cuentaNumerodocumento = cuentaNumerodocumento;
		this.cuentaNumerodocumentoModified = true;
	}

	/** 
	 * Sets the value of cuentaNumerodocumentoModified
	 */
	public void setCuentaNumerodocumentoModified(boolean cuentaNumerodocumentoModified)
	{
		this.cuentaNumerodocumentoModified = cuentaNumerodocumentoModified;
	}

	/** 
	 * Gets the value of cuentaNumerodocumentoModified
	 */
	public boolean isCuentaNumerodocumentoModified()
	{
		return cuentaNumerodocumentoModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Factura)) {
			return false;
		}
		
		final Factura _cast = (Factura) _other;
		if (idFactura != _cast.idFactura) {
			return false;
		}
		
		if (idFacturaModified != _cast.idFacturaModified) {
			return false;
		}
		
		if (fecha == null ? _cast.fecha != fecha : !fecha.equals( _cast.fecha )) {
			return false;
		}
		
		if (fechaModified != _cast.fechaModified) {
			return false;
		}
		
		if (total != _cast.total) {
			return false;
		}
		
		if (totalModified != _cast.totalModified) {
			return false;
		}
		
		if (cuentaTipodocumento == null ? _cast.cuentaTipodocumento != cuentaTipodocumento : !cuentaTipodocumento.equals( _cast.cuentaTipodocumento )) {
			return false;
		}
		
		if (cuentaTipodocumentoModified != _cast.cuentaTipodocumentoModified) {
			return false;
		}
		
		if (cuentaNumerodocumento == null ? _cast.cuentaNumerodocumento != cuentaNumerodocumento : !cuentaNumerodocumento.equals( _cast.cuentaNumerodocumento )) {
			return false;
		}
		
		if (cuentaNumerodocumentoModified != _cast.cuentaNumerodocumentoModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idFactura;
		_hashCode = 29 * _hashCode + (idFacturaModified ? 1 : 0);
		if (fecha != null) {
			_hashCode = 29 * _hashCode + fecha.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (fechaModified ? 1 : 0);
		_hashCode = 29 * _hashCode + Float.floatToIntBits(total);
		_hashCode = 29 * _hashCode + (totalModified ? 1 : 0);
		if (cuentaTipodocumento != null) {
			_hashCode = 29 * _hashCode + cuentaTipodocumento.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (cuentaTipodocumentoModified ? 1 : 0);
		if (cuentaNumerodocumento != null) {
			_hashCode = 29 * _hashCode + cuentaNumerodocumento.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (cuentaNumerodocumentoModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return FacturaPk
	 */
	public FacturaPk createPk()
	{
		return new FacturaPk(idFactura);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.tiendaenlinea.integracion.dto.Factura: " );
		ret.append( "idFactura=" + idFactura );
		ret.append( ", fecha=" + fecha );
		ret.append( ", total=" + total );
		ret.append( ", cuentaTipodocumento=" + cuentaTipodocumento );
		ret.append( ", cuentaNumerodocumento=" + cuentaNumerodocumento );
		return ret.toString();
	}

}
