/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.tiendaenlinea.integracion.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the proveedor table.
 */
public class ProveedorPk implements Serializable
{
	protected String idProveedor;

	protected String tipoDeIdentificacion;

	/** 
	 * Sets the value of idProveedor
	 */
	public void setIdProveedor(String idProveedor)
	{
		this.idProveedor = idProveedor;
	}

	/** 
	 * Gets the value of idProveedor
	 */
	public String getIdProveedor()
	{
		return idProveedor;
	}

	/** 
	 * Sets the value of tipoDeIdentificacion
	 */
	public void setTipoDeIdentificacion(String tipoDeIdentificacion)
	{
		this.tipoDeIdentificacion = tipoDeIdentificacion;
	}

	/** 
	 * Gets the value of tipoDeIdentificacion
	 */
	public String getTipoDeIdentificacion()
	{
		return tipoDeIdentificacion;
	}

	/**
	 * Method 'ProveedorPk'
	 * 
	 */
	public ProveedorPk()
	{
	}

	/**
	 * Method 'ProveedorPk'
	 * 
	 * @param idProveedor
	 * @param tipoDeIdentificacion
	 */
	public ProveedorPk(final String idProveedor, final String tipoDeIdentificacion)
	{
		this.idProveedor = idProveedor;
		this.tipoDeIdentificacion = tipoDeIdentificacion;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ProveedorPk)) {
			return false;
		}
		
		final ProveedorPk _cast = (ProveedorPk) _other;
		if (idProveedor == null ? _cast.idProveedor != idProveedor : !idProveedor.equals( _cast.idProveedor )) {
			return false;
		}
		
		if (tipoDeIdentificacion == null ? _cast.tipoDeIdentificacion != tipoDeIdentificacion : !tipoDeIdentificacion.equals( _cast.tipoDeIdentificacion )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idProveedor != null) {
			_hashCode = 29 * _hashCode + idProveedor.hashCode();
		}
		
		if (tipoDeIdentificacion != null) {
			_hashCode = 29 * _hashCode + tipoDeIdentificacion.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.tiendaenlinea.integracion.dto.ProveedorPk: " );
		ret.append( "idProveedor=" + idProveedor );
		ret.append( ", tipoDeIdentificacion=" + tipoDeIdentificacion );
		return ret.toString();
	}

}
